### ISSUE TITLE
Binding to pipe key?

### ISSUE THREAD

**Issue by Manypopes** [ccMSC/ckb#101]
I'm using UK key bindings on a US model K70, which mostly works fine, but I don't have a backslash or pipe key. I can easily rebind something to backslash using ckb, but the pipe key isn't included in the same dropdown. 

Is there a way to do this? If not could the pipe key be made available for binds?

Thanks, I'm really enjoying this software.

**Comment by ccMSC** [comment]
You mean shift+backslash? It should work the same way - hold shift and press the key that you assigned the backslash to.

**Comment by Manypopes** [comment]
Oh wow, yeah. Should have thought of that!
