### ISSUE TITLE
Taskbar icon invisible under GNOME

### ISSUE THREAD

**Issue by KraXarN** [ccMSC/ckb#108]
The little taskbar icon to show that the app is running is invisible under GNOME 3.14.
I can still click on the taskbar blindly to find it and when I do, it opens just fine.

**Comment by ccMSC** [comment]
Unfortunately this is a Qt issue and has been for some time. See: http://www.qtcentre.org/threads/56459-QSystemTrayIcon-and-linux
I can't fix it myself and I don't know of any workarounds, short of switching desktop environments.

**Comment by KraXarN** [comment]
Now it randomly appeared for some reason...
Anyway, since it's not an issue with this, I'll close the issue...
