### ISSUE TITLE
Scroll Lock LED Not Lighting

### ISSUE THREAD

**Issue by znorris** [ccMSC/ckb#111]
The scroll lock LED is not lighting up on my new K70. I have the latest release installed. Other functions seem to be fine. I tested the keyboard on a Windows computer and it toggles without issue. 

Currently running Ubuntu 14.04.
Firmware: 1.09
cbk-beta-v0.2

Please let me know what other information I can get to help identify the issue.

**Comment by ccMSC** [comment]
Most desktop environments don't use Scroll Lock anymore, so the light won't turn on even if you press the key. If you try it in a virtual terminal it should work.
