### ISSUE TITLE
ckb icon has a white background in notification area

### ISSUE THREAD

**Issue by thomassross** [ccMSC/ckb#112]
For some reason the ckb icon has a white background in my notification area:
![Notification Area](http://i.imgur.com/0ziLnsc.png)

**Comment by ccMSC** [comment]
Which OS/desktop environment? If you're using Unity, did you install libappindicator before building?

**Comment by thomassross** [comment]
Debian Testing, with XFCE 4.12

**Comment by ccMSC** [comment]
Tried with XFCE on Arch, not getting this issue. It's entirely possible that this is another bug in QTrayIcon (I already know of several), which unfortunately means there's nothing I can do to fix it. I may try to get rid of QTrayIcon entirely at some point and replace it with something more functional, but I can't promise anything yet.

**Comment by thomassross** [comment]
I found a fix, enabling window manager compositing and restarting ckb fixed it as described [here](https://github.com/telegramdesktop/tdesktop/issues/874)
