### ISSUE TITLE
Strafe support.

### ISSUE THREAD

**Issue by zetas** [ccMSC/ckb#113]
I'm about to buy a Strafe but I want to see if this firmware will work with it. I'm on OSX 10.10. I'm not sure since It's not an RGB model, I just want to make sure I can change the color and that it will actually work heh.

**Comment by zetas** [comment]
Nevermind, I guess the Strafe can't change colors heh.

**Comment by ccMSC** [comment]
Fairly certain the Strafe works on a similar protocol so the support for it could probably be added without too much trouble. However, I'd need testers and possibly USB captures. You're probably better off waiting for the Strafe RGB.
