### ISSUE TITLE
 [Linux] usbhid.quirks disabeling other usb devices

### ISSUE THREAD

**Issue by penetal** [ccMSC/ckb#115]
They might not be truly disabled, but at least some devices wont connect propperly.
After adding the first suggested cmdparameter line:

```
usbhid.quirks=0x1B1C:0x1B08:0x408,0x1B1C:0x1B09:0x400,0x1B1C:0x1B11:0x408,0x1B1C:0x1B12:0x400,0x1B1C:0x1B13:0x400,0x1B1C:0x1B17:0x400
```
I get this in my log when trying to connect my usbmouse:
```
aug. 25 14:30:42 ArcherBase kernel: quirks: can only take 4 arguments
aug. 25 14:30:42 ArcherBase kernel: usbhid: `0x1B1C:0x1B08:0x408' invalid for parameter `quirks'
```
So I removed all the devices except my own (easily found with lsusb) and everything was right again.
```
GRUB_CMDLINE_LINUX_DEFAULT="quiet usbhid.quirks=0x1B1C:0x1B11:0x408"
```

**Comment by ccMSC** [comment]
Yeah, I don't think the combined quirks line actually worked for anyone. I was hoping to make it simpler to use, but oh well. Old instructions are back now, along with an example of how to combine them for people who use more than one device.
