### ISSUE TITLE
Keyboard image is not properly scaled

### ISSUE THREAD

**Issue by jeepwk2** [ccMSC/ckb#116]
<img width="770" alt="screen shot 2015-08-25 at 11 34 24 am" src="https://cloud.githubusercontent.com/assets/13966789/9472884/6eb7eed2-4b1d-11e5-8d60-c4c0aaa3688e.png">

The image of the keyboard when modifying colors is not properly scaled and the keys do not correspond to the image. I am using a K70 RGB with Cherry MX Browns and a 13" Retina MacBook Pro.

**Comment by ccMSC** [comment]
Was fixed in e9a2d4d2b53e3549f6b62f5a50006016c99ef89f. Merged into master as of v0.2.1.
