### ISSUE TITLE
CKB high CPU use

### ISSUE THREAD

**Issue by mxanth** [ccMSC/ckb#118]
Was seeing excess CPU usage with update. Unchecking the "show animated" box on keyboard layout process CPU usage dropped dramatically. Not sure if this is unique to me but looks like a temporary fix.

**Comment by mxanth** [comment]
Same issue but when setting an animation to be triggered (pinwheel when holding space bar) seems to up CPU usage dramatically. When animation disabled CPU usage drops again.

**Comment by ccMSC** [comment]
The "show animated" checkbox does increase CPU usage, mostly because it has to constantly update the window. There's not much that can be done about that. See discussion in #67.

**Comment by securify** [comment]
Same issue here.  El Capitan on a new retina 13inch macbook pro.  CPU usage seems to jump while connected with spikes up to 45% on single core and when disconnected it fires more often  and is consistent about 15%.
