### ISSUE TITLE
Added latency to mouse

### ISSUE THREAD

**Issue by seguame** [ccMSC/ckb#119]
Whenever I activate CKB I notice that my mouse clicking gets lagged, at first I tought it was only on CKB interface, but it happens system wide, it is gone once I quit via interface.

Gnome 3.16.2
Archlinux Kernel 4.1.6-1

Update:
Reducing the framerate of the Kb reduces this lattency, but even at its lowest point it freezes from time to time

**Comment by ccMSC** [comment]
Does removing the animations entirely make a difference?

**Comment by seguame** [comment]
I created a new profile without animations and mouse clicks do not get lagged now.

**Comment by ccMSC** [comment]
In that case it's most likely related to the hardware or the USB bus. Make sure the firmware is up to date, try shuffling it around to a different USB port.
