### ISSUE TITLE
CKB High CPU Usage and Unable to Detect Keyboard

### ISSUE THREAD

**Issue by linjer** [ccMSC/ckb#123]
This is related to my previous issue filed #109 .

I installed the latest release of CKB and it's been mostly error free. But I also didn't get the chance to setup logging. As an aside, can you please enable logging by default, as the log files appear to be very small.

Different from the previous issue, the ckb-daemon CPU usage seems to be more around 50%. 
![screen shot 2015-09-10 at 11 50 34 am](https://cloud.githubusercontent.com/assets/1149070/9797926/d615d96c-57b2-11e5-9e68-df91f57af1af.png)

I'm typing this issue using the keyboard, but the CKB GUI says no keyboard detected. Lighting profiles are not set.

Environment:
OSX 10.10.3
K70 RGB

**Comment by linjer** [comment]
Killing the `ckb-daemon` process then restarting the CKB GUI does resume normal use.

**Comment by Dugthefreshest** [comment]
Killing that process definitely worked.

**Comment by Dugthefreshest** [comment]
It is note though, that after rebooting, had the same issue. My current mac version is 10.10.5

**Comment by ccMSC** [comment]
Fairly certain this is the same issue as #122.

**Comment by linjer** [comment]
I will be upgrading to 10.11 soon, which may bring a whole other world of issues. :P
