### ISSUE TITLE
K40 Keyboard support

### ISSUE THREAD

**Issue by debianmain1** [ccMSC/ckb#129]
Greetings!!!  As per request, I'm opening this & will dual post here & on the Corsair forms (unless you think that would be spamming the forum thread).

First information after installing clement's K90 driver with the K40 mod:

lsusb reports: Bus 003 Device 008: ID 1b1c:1b0e Corsair 

for f in /sys/bus/hid/devices/0003\:1B1C\:*/report_descriptor; do echo $f; xxd -g 1 "$f"; done
/sys/bus/hid/devices/0003:1B1C:1B0E.001B/report_descriptor
00000000: 05 01 09 06 a1 01 05 07 19 e0 29 e7 15 00 25 01 ..........)...%.
00000010: 75 01 95 08 81 02 75 08 95 01 81 01 05 07 19 00 u.....u.........
00000020: 2a ff 00 15 00 26 ff 00 75 08 95 06 81 00 05 08 *....&..u.......
00000030: 19 01 29 03 25 01 75 01 95 03 91 02 95 05 91 01 ..).%.u.........
00000040: c0 .
/sys/bus/hid/devices/0003:1B1C:1B0E.001C/report_descriptor
00000000: 05 0c 09 01 a1 01 05 0c 19 00 2a ff 0f 15 00 26 ..........*....&
00000010: ff 0f 75 10 95 02 81 00 c0 ..u......
/sys/bus/hid/devices/0003:1B1C:1B0E.001D/report_descriptor
00000000: 05 01 09 06 a1 01 05 07 19 e0 29 e7 15 00 25 01 ..........)...%.
00000010: 75 01 95 08 81 02 19 00 29 6f 15 00 25 01 75 01 u.......)o..%.u.
00000020: 95 70 81 02 c0

**Comment by cvuchener** [comment]
Does the keyboard have per-key led settings like other RGB keyboard or is it only a global setting (all the keys at once but per-profile)?

**Comment by debianmain1** [comment]
Does the keyboard have per-key led settings like other RGB keyboard or is it only a global setting (all the keys at once but per-profile)? 

Global setting seems to be all it has (per "M" key 1~3) Your edit is correct--

**Comment by debianmain1** [comment]
First software sniffer run.
In order:
Creat new profile2
Set M1 color
Set M2 Color
Set M3 color
Upload to keyboard
Assign G1 through G6 keys in M3
Upload to keyboard
Change back profile to profile1
close software

Seem to be running into not being able to rename the capture file & uploading it here--I will upload it to the forum & link here:  http://forum.corsair.com/forums/showthread.php?p=810811#post810811

**Comment by cvuchener** [comment]
It would have been better to have one capture per action. But actually most of the request are the same as for the K90, so I understand most of it. Knowing the exact colors you used would very helpful though.

The profile writing looks exactly like the K90 but I did not see any macro or key assignment. Are you sure you sent them to the hardware. Profiles are written three times during the capture, all are empty.

The only new request here is 51. It is sent three times (on for each profile I guess) when the profile are sent to the hardware. It is also sent when switching to a profile either by pressing the key or from the software (what you called "Creat new profile2"). There more of these request I cannot explain.

**Comment by cvuchener** [comment]
The high byte of wIndex could mean 0 for temporary color change, or 1 to 3 for changing a profile color. That leaves three bytes (low byte from wIndex and two bytes from wValue) that could be the color.

**Comment by cvuchener** [comment]
Can you try [this code](https://github.com/cvuchener/k40-set-color)? You need the development package for libusb-1.0 to compile it.
Test `./k40-set-color 255 0 0`, `./k40-set-color 0 255 0` or `./k40-set-color 0 0 255`. What happens?

**Comment by debianmain1** [comment]
Sorry I didn't include colors--do you want another set of runs with descrete actions for each?
The "Create new profile 2" is in the profile screen & I just selected "new profile" from the list.
This was a unlocked profile that I could edit--

**Comment by debianmain1** [comment]
I'll check out your code in a couple of minutes...

**Comment by debianmain1** [comment]
I had the .dev lib for libusb installed already--cd'd into the set-color folder & did a make...

dean@linux:~/Desktop/k40-set-color-master$ make
g++ -M -Wall -std=c++11 -g -O0 -I/usr/include/libusb-1.0   main.cpp > main.deps
g++ -c main.cpp -Wall -std=c++11 -g -O0 -I/usr/include/libusb-1.0   -o main.o
g++ main.o -lusb-1.0   -o k40-set-color


Looks good, but when I execute--nothing happens 
dean@linux:~/Desktop/k40-set-color-master$ sudo ./k40-set-color 0 255 0  = no change

**Comment by cvuchener** [comment]
> Sorry I didn't include colors--do you want another set of runs with descrete actions for each?

It is okay for me (maybe MSC will want more). But we need the exact color for each setting (give the numbers for red, green and blue).

> "Create new profile 2"

You cannot create or delete (hardware) profiles. You have three, one for each button. Clicking this button switched the current profile, that's all.

> Looks good, but when I execute--nothing happens 

No luck for the first guess (or do I have a bug in the program?). I saw a small error for the "red" channel, but it would not have affected the other test.

**Comment by cvuchener** [comment]
Please update k40-set-color.

Test setting a profile color (use options `-p1` or `-p2` or `-p3` and try different colors).

Then test setting the current color after some initialization request (from the first capture you provided). In the Makefile, there are two lines:

    #CXXFLAGS+=-DREQUEST_56
    #CXXFLAGS+=-DREQUEST_50

Try uncommenting one at a time, then both. For each test, recompile (`make -B`) and try setting the current color (without the `-p` option).

**Comment by ccMSC** [comment]
For starting out, I'm only really interested in the RGB commands. If it's like the K70, the hardware saving capabilities are probably pretty limited. Could you give me some captures for setting specific keys (i.e. A, S, D, etc...)?

**Comment by debianmain1** [comment]
Sounds good--I'll get both runs this evening--about 7pm pacific

**Comment by debianmain1** [comment]
Run without flags set.....

dean@linux:~/Desktop/k40-set-color-master$ sudo
'/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 255 0 0
dean@linux:~/Desktop/k40-set-color-master$ sudo
'/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 0 255 0
dean@linux:~/Desktop/k40-set-color-master$ sudo
'/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 0 0 255
dean@linux:~/Desktop/k40-set-color-master$ sudo
'/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 255 255 255
dean@linux:~/Desktop/k40-set-color-master$ sudo
'/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 255 255 100

All run the color(s) I expected blue, green, red, white, very light blue.

uncommenting CXXFLAGS+=-DREQUEST_56 locks up the application
uncommenting CXXFLAGS+=-DREQUEST_50 gives a status after request line.

dean@linux:~/Desktop/k40-set-color-master$ sudo
'/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 175 225 100
Status after request 50: 01 03 06 00 64 e1 af 03 00 01
dean@linux:~/Desktop/k40-set-color-master$
sudo '/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 0 0 255
Status after request 50: 01 03 06 00 64 e1 af 03 00 01
dean@linux:~/Desktop/k40-set-color-master$
sudo '/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 0 255 0
Status after request 50: 01 03 06 00 ff 00 00 03 00 01
dean@linux:~/Desktop/k40-set-color-master$ sudo
'/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 255 255 255
Status after request 50: 01 03 06 00 00 ff 00 03 00 01
dean@linux:~/Desktop/k40-set-color-master$ sudo
'/home/dean/Desktop/k40-set-color-master/k40-set-color' -p3 255 0 0 Status
after request 50: 01 03 06 00 ff ff ff 03 00 01

uncommenting both locks up the application.

Looks like DREQUEST_50 will give back possibly useful information.

After 3 or so color changes it will also lock up the app--force quitting
the terminal & restarting it will allow several more color changes until it
happens again..needs a "reset" ?


On Tue, Sep 29, 2015 at 1:45 AM, Clément Vuchener <notifications@github.com>
wrote:

> Please update k40-set-color.
>
> Test setting a profile color (use options -p1 or -p2 or -p3 and try
> different colors).
>
> Then test setting the current color after some initialization request
> (from the first capture you provided). In the Makefile, there are two lines:
>
> #CXXFLAGS+=-DREQUEST_56
> #CXXFLAGS+=-DREQUEST_50
>
> Try uncommenting one at a time, then both. For each test, recompile (make
> -B) and try setting the current color (without the -p option).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccMSC/ckb/issues/129#issuecomment-143990064>.
>



-- 
Cheers!!!
Dean Loros
Performance by Design Ltd.
autocrosser at http://forums.linuxmint.com

**Comment by debianmain1** [comment]
According to the website--it only has 36K worth of "storage", so not much
is right.....

OK, I'm going to set P1 with G1/W G2/A G3/S G4/D G5/O G5/M then do the same
for P2 & P3. will do a run for each profile.

Hope these are what you are looking for...

On Tue, Sep 29, 2015 at 2:09 AM, ccMSC <notifications@github.com> wrote:

> For starting out, I'm only really interested in the RGB commands. If it's
> like the K70, the hardware saving capabilities are probably pretty limited.
> Could you give me some captures for setting specific keys (i.e. A, S, D,
> etc...)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccMSC/ckb/issues/129#issuecomment-144000075>.
>



-- 
Cheers!!!
Dean Loros
Performance by Design Ltd.
autocrosser at http://forums.linuxmint.com

ÔÃ²¡ÿÿùÙ<Vøf**<‰ÿÿÿÿ	ƒÙ<Vþ£**9<‰ÿÿÿÿ	ƒâ<V×**<‰ÿÿÿÿ	ƒâ<VSv**9<‰ÿÿÿÿ	ƒâ<VY³**<‰ÿÿÿÿ	ƒè<VdÕ**9<‰ÿÿÿÿ	ƒè<VŸ7**<‰ÿÿÿÿ	ƒè<V¥t**9<‰ÿÿÿÿ	ƒï<Vù**<‰ÿÿÿÿ	ƒ@ï<V4ò**9<‰ÿÿÿÿ	ƒï<V:/**<‰ÿÿÿÿ	ƒõ<V!ã	**9<‰ÿÿÿÿ	ƒ€õ<V€³
**<‰ÿÿÿÿ	ƒõ<V†ð
**9<‰ÿÿÿÿ	ƒü<V¸**<‰ÿÿÿÿ	ƒü<V´Ý	**9<‰ÿÿÿÿ	ƒü<Vº
**<‰ÿÿÿÿ	ƒ=Vy**9<‰ÿÿÿÿ	ƒ=VPÛ**<‰ÿÿÿÿ	ƒ=VV**9<‰ÿÿÿÿ	ƒ	=Vîì$$pNŠÿÿÿÿ@	=VîìpNŠÿÿÿÿ
=V¸$$¸ú®‰ÿÿÿÿ€À
=V¸¸ú®‰ÿÿÿÿ€
=V¸¸ú®‰ÿÿÿÿ€
=V¸$$¸ú®‰ÿÿÿÿ@%
=V¸AA¸ú®‰ÿÿÿÿ%_
=V¸¸ú®‰ÿÿÿÿ
=VSW$$%=‰ÿÿÿÿ€À
=VSW%=‰ÿÿÿÿ€
=VSW%=‰ÿÿÿÿ€
=V|$$ðê¹‰ÿÿÿÿ€À
=V|ðê¹‰ÿÿÿÿ€
=V|ðê¹‰ÿÿÿÿ€
=V|$$%=‰ÿÿÿÿ@%
=V|AA%=‰ÿÿÿÿ%ÐÑÒÓÔÕ
=V|%=‰ÿÿÿÿ
=V½¡$$:‰ÿÿÿÿ€À
=V½¡:‰ÿÿÿÿ€
=V½¡:‰ÿÿÿÿ€
=V½¡$$:‰ÿÿÿÿ@3Y
=V½¡:‰ÿÿÿÿ
=VÕ•	$$ˆø®‰ÿÿÿÿ@%
=VÕ•	AAˆø®‰ÿÿÿÿ%_
=VÕ•	ˆø®‰ÿÿÿÿ
=V5$$à“:‰ÿÿÿÿ€À
=V5à“:‰ÿÿÿÿ€
=V5à“:‰ÿÿÿÿ€
=V?à
$$K²‰ÿÿÿÿ€À
=V?à
K²‰ÿÿÿÿ€
=V?à
K²‰ÿÿÿÿ€
=V?à
$$ÈwÑ‰ÿÿÿÿ@%
=V?à
AAÈwÑ‰ÿÿÿÿ%ÐÑÒÓÔÕ
=V?à
ÈwÑ‰ÿÿÿÿ=V@=$$ØÊ	Šÿÿÿÿ€À=V@=ØÊ	Šÿÿÿÿ€=V@=ØÊ	Šÿÿÿÿ€=V@=$$ØÊ	Šÿÿÿÿ@3$=V@=ØÊ	Šÿÿÿÿ=VX1$$`èÄ‰ÿÿÿÿ@%=VX1AA`èÄ‰ÿÿÿÿ%_=VX1`èÄ‰ÿÿÿÿ=V™Ð$$ˆÑŠÿÿÿÿ€À=V™ÐˆÑŠÿÿÿÿ€=V™ÐˆÑŠÿÿÿÿ€=VÂ{$$ðê¹‰ÿÿÿÿ€À=VÂ{ðê¹‰ÿÿÿÿ€=VÂ{ðê¹‰ÿÿÿÿ€=VÂ{$$0¯‰ÿÿÿÿ@%=VÂ{AA0¯‰ÿÿÿÿ%ÐÑÒÓÔÕ=VÂ{0¯‰ÿÿÿÿ=V	$$èŠÿÿÿÿ€À=V	èŠÿÿÿÿ€=V	èŠÿÿÿÿ€=V	$$èŠÿÿÿÿ@3l«Y=V	èŠÿÿÿÿ=V
$$ˆÑŠÿÿÿÿ@0=V
ˆÑŠÿÿÿÿ=V4Î	**<‰ÿÿÿÿ	ƒ=Vjó**9<‰ÿÿÿÿ	ƒ=Vo0**<‰ÿÿÿÿ	ƒ=V–	**9<‰ÿÿÿÿ	ƒ
ÔÃ²¡ÿÿù*=VÁ **9<‰ÿÿÿÿ	ƒ*=VÇÝ**<‰ÿÿÿÿ	ƒ/=VTä$$¨–¯‰ÿÿÿÿ@/=VTä¨–¯‰ÿÿÿÿ/=Ve›##pôú‰ÿÿÿÿ	/=Vq$$@”¯‰ÿÿÿÿ@3$/=Vq@”¯‰ÿÿÿÿ3=V–ñ**9<‰ÿÿÿÿ	ƒ4=V£È**<‰ÿÿÿÿ	ƒ4=V©**9<‰ÿÿÿÿ	ƒ:=V/)**<‰ÿÿÿÿ	ƒ;=V$**9<‰ÿÿÿÿ	ƒ;=V*I**<‰ÿÿÿÿ	ƒ@=V‹ä**9<‰ÿÿÿÿ	ƒ@@=VÌƒ**<‰ÿÿÿÿ	ƒ@=VÒÀ**9<‰ÿÿÿÿ	ƒG=V$**<‰ÿÿÿÿ	ƒ€G=Vkø**9<‰ÿÿÿÿ	ƒG=Vq5**<‰ÿÿÿÿ	ƒO=V	
**9<‰ÿÿÿÿ	ƒO=VDl**<‰ÿÿÿÿ	ƒO=VDl**9<‰ÿÿÿÿ	ƒT=Vëã
**<‰ÿÿÿÿ	ƒU=Vò}**9<‰ÿÿÿÿ	ƒU=Vò}**<‰ÿÿÿÿ	ƒY=Vf3$$ÈwÑ‰ÿÿÿÿ\ë6¯@Y=Vf3ÈwÑ‰ÿÿÿÿY=VË@$$ÐU¬‰ÿÿÿÿ€ÀY=VË@ÐU¬‰ÿÿÿÿ€Y=VË@ÐU¬‰ÿÿÿÿ€Y=VË@$$ÐU¬‰ÿÿÿÿ@%Y=VË@AAÐU¬‰ÿÿÿÿ%_Y=VË@ÐU¬‰ÿÿÿÿY=Và
$$÷;‰ÿÿÿÿ€ÀY=Và
÷;‰ÿÿÿÿ€Y=Và
÷;‰ÿÿÿÿ€Z=VõH$$èä:‰ÿÿÿÿ€ÀZ=VõHèä:‰ÿÿÿÿ€Z=VõHèä:‰ÿÿÿÿ€Z=VõH$$èä:‰ÿÿÿÿ@%Z=VõHAAèä:‰ÿÿÿÿ%ÐÑÒÓÔÕZ=VõHèä:‰ÿÿÿÿZ=V6è$$ˆÑŠÿÿÿÿ€ÀZ=V6èˆÑŠÿÿÿÿ€Z=V6èˆÑŠÿÿÿÿ€Z=V6è$$ˆÑŠÿÿÿÿ@3YZ=V6èˆÑŠÿÿÿÿZ=VMÜ$$X´¸‰ÿÿÿÿ@%Z=VMÜAAX´¸‰ÿÿÿÿ%_Z=VMÜX´¸‰ÿÿÿÿZ=VŽ{$$pnB‰ÿÿÿÿ€ÀZ=VŽ{pnB‰ÿÿÿÿ€Z=VŽ{pnB‰ÿÿÿÿ€Z=V·&$$àŠÿÿÿÿ€ÀZ=V·&àŠÿÿÿÿ€Z=V·&àŠÿÿÿÿ€Z=V·&$$àŠÿÿÿÿ@%Z=V·&AAàŠÿÿÿÿ%ÐÑÒÓÔÕZ=V·&àŠÿÿÿÿZ=VøÅ
$$pnB‰ÿÿÿÿð›Q°€ÀZ=VøÅ
pnB‰ÿÿÿÿ€Z=VøÅ
pnB‰ÿÿÿÿ€Z=VøÅ
$$pnB‰ÿÿÿÿ@3$Z=VøÅ
pnB‰ÿÿÿÿZ=Vº$$àŠÿÿÿÿ@%Z=VºAAàŠÿÿÿÿ%_Z=VºàŠÿÿÿÿZ=VQY$$pnB‰ÿÿÿÿ€ÀZ=VQYpnB‰ÿÿÿÿ€Z=VQYpnB‰ÿÿÿÿ€[=V:Â$$K²‰ÿÿÿÿ€À[=V:ÂK²‰ÿÿÿÿ€[=V:ÂK²‰ÿÿÿÿ€[=V:Â$$¨–¯‰ÿÿÿÿ@%[=V:ÂAA¨–¯‰ÿÿÿÿ%ÐÑÒÓÔÕ[=V:Â¨–¯‰ÿÿÿÿ[=V{a$$K²‰ÿÿÿÿ€À[=V{aK²‰ÿÿÿÿ€[=V{aK²‰ÿÿÿÿ€[=V{a$$K²‰ÿÿÿÿ@3l«Y[=V{aK²‰ÿÿÿÿ[=V“U$$xF
Šÿÿÿÿ@0[=V“UxF
Šÿÿÿÿb=V¼**9<‰ÿÿÿÿ	ƒb=Vý¤**<‰ÿÿÿÿ	ƒb=Vý¤**9<‰ÿÿÿÿ	ƒc=V9**<‰ÿÿÿÿ	ƒ
ÔÃ²¡ÿÿù~=VgÀ**<‰ÿÿÿÿ	ƒ~=VgÀ**9<‰ÿÿÿÿ	ƒ‡=V8”**<‰ÿÿÿÿ	ƒ‡=Vy3**9<‰ÿÿÿÿ	ƒ‡=Vp**<‰ÿÿÿÿ	ƒŒ=V{
**9<‰ÿÿÿÿ	ƒ=V€Ø**<‰ÿÿÿÿ	ƒ=V†**9<‰ÿÿÿÿ	ƒ‘=V|	**<‰ÿÿÿÿ	ƒ@‘=V½¨**9<‰ÿÿÿÿ	ƒ‘=V½¨**<‰ÿÿÿÿ	ƒ—=Vp**9<‰ÿÿÿÿ	ƒ€—=V<Ò**<‰ÿÿÿÿ	ƒ—=V<Ò**9<‰ÿÿÿÿ	ƒœ=V*&**<‰ÿÿÿÿ	ƒ=V%F**9<‰ÿÿÿÿ	ƒ=V%F**<‰ÿÿÿÿ	ƒ¡=Vb**9<‰ÿÿÿÿ	ƒ¢=V]6**<‰ÿÿÿÿ	ƒ¢=Vcs**9<‰ÿÿÿÿ	ƒ¦=V$B$$H£?‰ÿÿÿÿ@¦=V$BH£?‰ÿÿÿÿ§=VH
$$pÞ‰ÿÿÿÿ€À§=VH
pÞ‰ÿÿÿÿ€§=VH
pÞ‰ÿÿÿÿ€§=VH
$$pÞ‰ÿÿÿÿ@%§=VH
AApÞ‰ÿÿÿÿ%_§=VH
pÞ‰ÿÿÿÿ§=V‰¬$$°ª?‰ÿÿÿÿ€À§=V‰¬°ª?‰ÿÿÿÿ€§=V‰¬°ª?‰ÿÿÿÿ€§=V²W$$x&Ø‰ÿÿÿÿ€À§=V²Wx&Ø‰ÿÿÿÿ€§=V²Wx&Ø‰ÿÿÿÿ€§=V²W$$x&Ø‰ÿÿÿÿ@%§=V²WAAx&Ø‰ÿÿÿÿ%ÐÑÒÓÔÕ§=V²Wx&Ø‰ÿÿÿÿ§=Vóö$$p¾“‰ÿÿÿÿ€À§=Vóöp¾“‰ÿÿÿÿ€§=Vóöp¾“‰ÿÿÿÿ€§=Vóö$$p¾“‰ÿÿÿÿ@3Y§=Vóöp¾“‰ÿÿÿÿ§=Vë$$pNŠÿÿÿÿ@%§=VëAApNŠÿÿÿÿ%_§=VëpNŠÿÿÿÿ§=VLŠ
$$èUÃ‰ÿÿÿÿ€À§=VLŠ
èUÃ‰ÿÿÿÿ€§=VLŠ
èUÃ‰ÿÿÿÿ€§=Vu5$$È•ù‰ÿÿÿÿ€À§=Vu5È•ù‰ÿÿÿÿ€§=Vu5È•ù‰ÿÿÿÿ€§=Vu5$$È•ù‰ÿÿÿÿ@%§=Vu5AAÈ•ù‰ÿÿÿÿ%ÐÑÒÓÔÕ§=Vu5È•ù‰ÿÿÿÿ§=V¶Ô$$¨ÉŠÿÿÿÿ€À§=V¶Ô¨ÉŠÿÿÿÿ€§=V¶Ô¨ÉŠÿÿÿÿ€§=V¶Ô$$¨ÉŠÿÿÿÿ@3$§=V¶Ô¨ÉŠÿÿÿÿ¨=V†$$°J<‰ÿÿÿÿ@%¨=V†AA°J<‰ÿÿÿÿ%_¨=V†°J<‰ÿÿÿÿ¨=VÎ%$$PÄ¸‰ÿÿÿÿ€À¨=VÎ%PÄ¸‰ÿÿÿÿ€¨=VÎ%PÄ¸‰ÿÿÿÿ€¨=VøÐ$$€ú‰ÿÿÿÿ€À¨=VøÐ€ú‰ÿÿÿÿ€¨=VøÐ€ú‰ÿÿÿÿ€¨=VøÐ$$€ú‰ÿÿÿÿ@%¨=VøÐAA€ú‰ÿÿÿÿ%ÐÑÒÓÔÕ¨=VøÐ€ú‰ÿÿÿÿ¨=V8p$$pî¯‰ÿÿÿÿ€À¨=V8ppî¯‰ÿÿÿÿ€¨=V8ppî¯‰ÿÿÿÿ€¨=V8p$$pî¯‰ÿÿÿÿ@3l«Y¨=V8ppî¯‰ÿÿÿÿ¨=VPd$$pþ‰ÿÿÿÿ@0¨=VPdpþ‰ÿÿÿÿ­=V¢**<‰ÿÿÿÿ	ƒ­=VÝj**9<‰ÿÿÿÿ	ƒ­=Vâ§**<‰ÿÿÿÿ	ƒ®=Vzw**9<‰ÿÿÿÿ	ƒ

**Comment by debianmain1** [comment]
As I use the software in windows, it seems that Corsair is a bit optimistic
about how this keyboard changes color--not on a per key basis--just per
profile globally on all keys. I have not tried any animations in Windows
(not really a windows user), but I will explore the limits of the software
to see what is "really" possible. I do know it will record & save macros
per profile (have seen some output on this-if you want a capture of this
I'll get it done) & will report back as to what else it can do.

On Tue, Sep 29, 2015 at 2:09 AM, ccMSC <notifications@github.com> wrote:

> For starting out, I'm only really interested in the RGB commands. If it's
> like the K70, the hardware saving capabilities are probably pretty limited.
> Could you give me some captures for setting specific keys (i.e. A, S, D,
> etc...)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccMSC/ckb/issues/129#issuecomment-144000075>.
>



-- 
Cheers!!!
Dean Loros
Performance by Design Ltd.
autocrosser at http://forums.linuxmint.com

**Comment by debianmain1** [comment]
OK--what it can do is pulse the preset color (vary brightness dim to max
with a variable time setting) or do a variable color change through the
spectrum, also with a variable time delay--there is also an option to do
this only after Idle (no setting for how long idle time is-looks like 30
sec of non-useage) or on all the time. I set it to P2 to see if it needs
the windows driver to do this & it looks like it does.

So, rather more basic than it's more expensive brothers, but I can see that
some interesting things could be done with scripts.

On Tue, Sep 29, 2015 at 2:09 AM, ccMSC <notifications@github.com> wrote:

> For starting out, I'm only really interested in the RGB commands. If it's
> like the K70, the hardware saving capabilities are probably pretty limited.
> Could you give me some captures for setting specific keys (i.e. A, S, D,
> etc...)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccMSC/ckb/issues/129#issuecomment-144000075>.
>



-- 
Cheers!!!
Dean Loros
Performance by Design Ltd.
autocrosser at http://forums.linuxmint.com

**Comment by debianmain1** [comment]
What do you guys want checked next?

**Comment by ccMSC** [comment]
Hmm...if that's the case I may not have the ability to add it in ckb, honestly. The driver is meant to handle per-key RGB animations and won't really do anything else without a huge rewrite. I think you're better off helping Clement get it into a kernel driver since it seems like the keyboard has more in common with the K90 anyway.

**Comment by debianmain1** [comment]
OK--its looking like the K90 driver is working well for this keyboard & Clement has got a good percentage of its capabilities figured out. Will keep posting here if you are interested......
