### ISSUE TITLE
Start CKB without GUI / Start anims without ckb ? 

### ISSUE THREAD

**Issue by Perdouille** [ccMSC/ckb#14]
Hello 

Is there a way to start animations / key rebinding at boot ? I use ArchLinux, I've set ckb-daemon to start at boot with Systemd, but how can I make that CKB start in the background ?

Sorry for my maybe bad English, thanks :)

**Comment by ccMSC** [comment]
Depends on your desktop environment. Most DEs have a setting where you can auto-start apps as soon as you log in, which is what you'd want to do. I just added an option to hide ckb at startup using the `--background` option.

**Comment by Perdouille** [comment]
Ok thanks a lot !
