### ISSUE TITLE
M65 RGB Scrolling Issue 

### ISSUE THREAD

**Issue by samcat116** [ccMSC/ckb#144]
I have an M65 RGB. It seems to be detected fine, but the scrolling is not working properly. The buttons are bound correctly, but it only seems to register like 1 out of ever 20 scrolls.

**Comment by ccMSC** [comment]
Sounds like it might be a hardware issue. Does it have the problem on a Windows machine?

**Comment by samcat116** [comment]
It works perfectly fine on windows. I'm on the newest firmware for the mouse and the latest version of OS X.
