### ISSUE TITLE
Strafe RGB support release

### ISSUE THREAD

**Issue by SicVolo** [ccMSC/ckb#146]
Could you pull Strafe into the main branch?

**Comment by ccMSC** [comment]
Waiting to hear back from a tester re. Sabre RGB support. Once that's done I'll update the version to 0.2.2 and release it into the master branch. If I don't hear back in the next 3-5 days I'll temporarily remove the Sabre and release it anyway.

**Comment by ccMSC** [comment]
Ok, I still haven't heard back yet. I just finished up the last feature I wanted for v0.2.2, so barring any major bug discoveries I'll remove the Sabre for now and release the new version tomorrow.
