### ISSUE TITLE
Switching profiles via keyboard key

### ISSUE THREAD

**Issue by grosen** [ccMSC/ckb#15]
Does the program support this? I do not see the ability to do this

**Comment by ccMSC** [comment]
Only supported on the K95 at the moment. Support for this on other boards is coming when key rebinding is finished, probably in 1-2 weeks.

**Comment by ccMSC** [comment]
As of commit bbac155dd511b1635bdcd317405d0cd01bf0c071 you can now assign any key to switch modes. Feel free to open a new issue if you have any problems with it.
