### ISSUE TITLE
Keyboard not detected 

### ISSUE THREAD

**Issue by Hant-Teur** [ccMSC/ckb#154]
Hello, first of all thanks for the great work on this app, I posted here (i dont know if it is right) to ask a little question, in fact my keyboard is not detected by the driver when i reboot my iMac, i have to take it off and put it on a few times and when i am lucky it get´s detected, I downloaded the driver directly because with Qtcreator there is a failure message saying a thing like ''not supported Mac OS X 10.10'' (it appears when i do cmb+b) I have a corsair k65 RGB.
If you need any other pieces of information let me know, thanks ! :) (It is because i can not modify stuff with Qtsource that i am a bit ''blocked'')

**Comment by ccMSC** [comment]
Same issue as #122? Can you test whether or not it happens even if you remove the ckb application?

**Comment by Hant-Teur** [comment]
Yes but it is very difficult to get the keyboard detected when the computer reboots, it seems to be a lot of luck, yes i try to re-install now !

**Comment by Hant-Teur** [comment]
Yes I confirm when i reinstall cab (2.2 version) the keyboards is instantly detected and the settings/bindings that I did before appeared.
