### ISSUE TITLE
~` key types like a ±§ key on OS X

### ISSUE THREAD

**Issue by BenLeggieroNCR** [ccMSC/ckb#162]
Before I installed _ckb_, every key typed just fine. Now, every key types just fine except the one to the left of the <kbd>!<br/>1</kbd> key. Now, that key is acting as if it is a <kbd>±<br/>§</kbd> key (typing it results in `§`, and holding shift and typing it results in `±`). Quitting _ckb_ does not fix this, nor does restarting it.

**Comment by BenLeggieroNCR** [comment]
Turns out it defaults to European keyboards. Strange, since I told OS X it was American layout before installing ckb. Consider this issue that **ckb ignores keyboard locale on install.**

**Comment by ccMSC** [comment]
Not sure it's possible to fix that, unfortunately. It should ask you to specify your keyboard layout the first time you run it (as of v0.2.2 - if you installed an earlier beta, it wouldn't).

**Comment by BenLeggieroNCR** [comment]
Awww, sad. You can't ask OS X for its current locale? :/

**Comment by ccMSC** [comment]
There is a locale detection which works on Linux and it used to work on OSX, but I think it stopped working with Yosemite. I'll revisit it in the future, but for now it's not a high enough priority.

**Comment by soybeanyoung** [comment]
I suffered from the same issue, but I found we could change the layout in the settings of ckb.

![image](https://cloud.githubusercontent.com/assets/15900605/11321574/d0945e7c-9093-11e5-8b9c-4eb59953c6bc.png)

The default one is European, so that is why we have such problems.

**Comment by darkcrux** [comment]
Oh that worked! was pulling my hair looking for a fix! Thanks!
