### ISSUE TITLE
Latin American Layout

### ISSUE THREAD

**Issue by carlosmprzmx** [ccMSC/ckb#165]
Do you plan give support for the Latin American layout?

Actually i'm using you software in a iMac OS X 10.11.1 with a Corsair K70 RGB and run amazing!

Thank you guys!

**Comment by ccMSC** [comment]
I usually add them on a per-request basis. Which layout specifically do you want?

**Comment by carlosmprzmx** [comment]
Thanks for the answer.

I have the Corsair K70 RGB with the latin american layout, this -> 
![image](https://cloud.githubusercontent.com/assets/1895549/11317004/4797d55a-8fe3-11e5-8898-97418337e05b.png)

By the way, you are doing a great job!

**Comment by carlosmprzmx** [comment]
I decide take a picture if the keyboard.

![2015-11-21 00 11 47](https://cloud.githubusercontent.com/assets/1895549/11317068/cdfea29e-8fe4-11e5-907d-fb669e5de5c4.jpg)

i hope the photo be more useful

**Comment by ccMSC** [comment]
Implemented in 810b8db89fd0750f65da9c29c244afd9329b1744. Let me know if you have any issues with it.

**Comment by carlosmprzmx** [comment]
Instalado todo parece estar bien.
