### ISSUE TITLE
Cannot upgrade to v1.3.0 firmware

### ISSUE THREAD

**Issue by ryanaltvater** [ccMSC/ckb#167]
I just purchased the Corsair K70 RGB keyboard, and I receive the following message every time CKB asks if I want to upgrade to 1.3.0:

"There was a problem with the downloaded file.
Please try again later."

**Comment by ccMSC** [comment]
Seems Corsair recently updated them to 1.33. I'm going to test it out, if there are no problems then I'll update the firmware database.

**Comment by ccMSC** [comment]
No issues found, works fine with the current ckb version. I've updated the firmware list so it will recognize the new versions now.
