### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by Astaoth** [ccMSC/ckb#171]
Hi,

Do you plan to support also gaming mouses ? Like the Corsair M90 ?

Best regards

**Comment by carlosmprzmx** [comment]
@Astaoth Corsair M90 don't have RGB lights, this software is for control RGB lights :confused:

**Comment by Astaoth** [comment]
In the README, in the "Usage" section, there is written : 
"- Customizable key bindings
- Per-key lighting and animation
- Reactive lighting
- Multiple profiles/modes with hardware save function
- Adjustable mouse DPI with ability to change DPI on button press"

It seems a little more than only RGB light control.

On the Corsair M90, there are lights, internal memory, extra keys and adjustable DPI. Maybe it is possible to control this feature from this software ?

**Comment by ccMSC** [comment]
Non-RGB support hasn't really been possible since they use a different USB protocol (only exception being the STRAFE) and in some cases they don't work the same way that the RGB versions do. Unless you or somebody else has the ability to add code for it, it's not likely that the M90 will get supported.

**Comment by Astaoth** [comment]
Oh, I see :(. I'm not sure I have the skills to decode the USB protocol, maybe can you give me some advice ?

**Comment by ccMSC** [comment]
The way I did it was to run Windows in a virtual machine, connect the keyboard/mouse to it, then capture the USB packets with Wireshark. After that it's just a matter of testing the inputs and outputs until you figure out which packet does what.

**Comment by Astaoth** [comment]
Thank you, I will try to figure out the protocol.
