### ISSUE TITLE
CKB wont open and menu bar icon is gone

### ISSUE THREAD

**Issue by Mikeeeey** [ccMSC/ckb#173]
- Using a K65 RGB
- Running El Capitan 10.11.1
- Mid 2014 5k iMac. (i7-4790k + R9 M295X + SSD)

Downloaded CKB, changed the lights on my K65 and worked fine, went to settings and said to hide the menu bar icon and now I can never open it back up, I go to Applications -> CKB and it still won't open, I've tried terminate the process and re-open but still nothing, tried reboots but nope.

Lastly, uninstalled it completely and reinstalled it, same thing it remembered my profiles though and I can't get the tray bar icon back up or to open CKB at all. 

Any suggestions? 

PS - I know you've heard this a lot, but again THANKS for developing this, Corsair needs to pick up their act.

**Comment by ccMSC** [comment]
You may need to delete the settings entirely. They can be found in `~/Library/Application Support/com.ckb.ckb.plist`. Make sure you've closed ckb via System Monitor first.

**Comment by Mikeeeey** [comment]
There is no com.ckb.ckb.plist in my ApplicationSupport folder? 

When I terminate it from Activity monitor it just pops right back up.

**Comment by ccMSC** [comment]
Sorry, it's actually in `~/Library/Preferences`, not Application Support.

**Comment by helloworld82** [comment]
I'm having the same issue, and the com.ckb.ckb.plist file isn't in the Application Support folder.
