### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by prototoon** [ccMSC/ckb#175]
I have the same scrolling issues with my m65, I've seen two other threads that have the same problem but when i read them i totally have no idea how to fix it? Could i get some help? thanks

**Comment by ccMSC** [comment]
There's a fix for it currently in the testing repository. I can provide a binary if you don't want to compile it from source.

**Comment by prototoon** [comment]
that would be great :) please do, thanks

**Comment by ccMSC** [comment]
Hi, sorry for the delay, I have the binary version ready: https://dl.dropboxusercontent.com/u/16424004/ckb/ckb%20beta%20v0.2.2%2Bt04.zip

There's a new "More Settings" screen which has an option to disable scroll wheel acceleration. Try checking that option and see if the problem is solved.

**Comment by prototoon** [comment]
thanks so much :)

**Comment by prototoon** [comment]
its working perfectly now
