### ISSUE TITLE
CKB daemon icon is on top of the 'x' used to close windows

### ISSUE THREAD

**Issue by chrisgogreen** [ccMSC/ckb#182]
After installing on Ubuntu 14.04 I noticed that the CKB daemon icon is always on top of the close window x, I have to move the window to close them.

**Comment by tatokis** [comment]
If I understood this correctly, do you have the libappindicator-dev package installed?
If not install it and recompile ckb.

**Comment by chrisgogreen** [comment]
First I restarted and the ckb tray icon disappeared completely. Then I installed libappindicator-dev and recompiled, now the icon is in the correct location in the tray. Thanks!

**Comment by bigBearSingh** [comment]
Note that after installing libappindicator-dev and recompiled, I had to restart the desktop for tray icon to appear correctly, or maybe this step is obvious. Thanks all.
