### ISSUE TITLE
Bind G keys to insert custom text

### ISSUE THREAD

**Issue by chrisgogreen** [ccMSC/ckb#183]
How can I bind the G keys on my K95 to insert snippets of text? It looks like I could use the Launch program on keypress feature, is that the best way?

**Comment by tatokis** [comment]
Only way I can think of right now is to install the xautomation package and then use the "Launch program on keypress" with xte.
Example: 
```
xte 'str Hello, World!'
```
Maybe this could be a built in feature of ckb in the future.

**Comment by chrisgogreen** [comment]
I will try this and report back.

**Comment by chrisgogreen** [comment]
I ended up making a bash script with:

```
#!/bin/bash

cat /home/username/code/snippets/bare_method.txt | xclip -i -selection clipboard
xte 'keydown Control_L' 'key v' 'keyup Control_L'

```

then binding the G key to Launch program on key press with:

```
/home/username/code/snippets/bare_method
```

**Comment by ccMSC** [comment]
Yeah, you can also use `xdotool type 'your text here'`.

Text macros are a planned feature, but they've been bumped down quite a lot due to lack of demand. They'll be available eventually.

**Comment by chrisgogreen** [comment]
Thank you for mentioning xdotool. I'll close this issue.
