### ISSUE TITLE
Indicators don't emit light

### ISSUE THREAD

**Issue by kimamb** [ccMSC/ckb#185]
[STRAFE RGB SCANDINAVIAN]
All of the top row buttons don't emit light.

I've tried changing the settings under top row; still no luck.
Even the corsair logo is gone!
I have problems finding the brightness key because of my dark room.

What could be the cause of this?

(It works perfectly in windows)

**Comment by SicVolo** [comment]
are you talking about the brightness and the windows lock buttons, or the esc through f12 row?
Funny thing, I did not realize corsair logo was supposed to be lit. I guess we got to fix this.

**Comment by kimamb** [comment]
I didn't thought that either, before I tried playing witcher on my windows partition.

**Comment by ccMSC** [comment]
Check your Performance tab in the keyboard settings - it contains colors for those lights. Make sure the indicators are enabled and are set to the colors you're expecting.

**Comment by SicVolo** [comment]
These don't work on my system either. Apparently the brightness button, the windows lock button and the corsair logo use USB codes unique to Strafe RGB. I just forgot about them when I wrote the code. I'll get it fixed.

**Comment by zhouti1993** [comment]
same problem for my strafe RGB.looking forward to new update.Thanks al lot!!

**Comment by SicVolo** [comment]
Fixed. Just sent a pull request to the testing branch of this repo from my fork. @ccMSC keep us updated, pls.

**Comment by zhouti1993** [comment]
i don't know how to do i.Can u teach me to operate more specifically? Thank u very much!

**Comment by zhouti1993** [comment]
In order to install the new program,Do i  have to install Qt5?

**Comment by zhouti1993** [comment]
Finally I solved out˜~  Wow amazing
  Guines@!! Engineering

**Comment by zhouti1993** [comment]
HAHA  works perfect!!!

**Comment by kimamb** [comment]
@SicVolo Thank you!

**Comment by ccMSC** [comment]
Merged changes into testing, thanks!

**Comment by kimamb** [comment]
The corsair logo somehow became white after rebooting, in all of the profiles I changed its colour in.

**Comment by SicVolo** [comment]
That's probably because it had not had a color 'saved' in the past. Try setting it to a color in CKB and use "save to hardware" button to have it default to that color when booting, or when not controlled by CKB. Mine seems to work fine (boots red). The indicator color can be controlled via the performance tab.

**Comment by kimamb** [comment]
Ah

**Comment by shazron** [comment]
Works great for me from the testing branch, thanks @SicVolo [Strafe RGB US]
