### ISSUE TITLE
[Thanks!] This isn't an issue, but I wanted you to see it anyway :D

### ISSUE THREAD

**Issue by Locknlol** [ccMSC/ckb#186]
Hi, happy holidays! I'd just like to say thank you so much for this amazing project! I just recently switched to linux as my daily OS, and received the Corsair Scimitar and Corsair Strafe for Christmas from my mother. I was super worried that I would be forced to return to windows to fully utilize this keyboard/mouse, but after a super quick google, your project was on top, and I am so thrilled that it took no time at all to install and configure. I'm now able to fully utilize my keyboard and mouse!

So thank you! Thank you for the time you spent on this, and the time you plan on spending on this. I am so thrilled! I wish you the best, and have a wonderful 2016!

**Comment by ccMSC** [comment]
Glad you liked it! Hope you have a great year too :)
