### ISSUE TITLE
Retina icon in menubar

### ISSUE THREAD

**Issue by grosen** [ccMSC/ckb#19]
OS X

**Comment by ccMSC** [comment]
Is your version of Qt up to date? According to this it was fixed in version 5.4: https://bugreports.qt.io/browse/QTBUG-33441

I don't have a retina display so I can't test it, but the image file is more than large enough.

**Comment by ccMSC** [comment]
Hello? Can you tell me what version of Qt you're using?

You can find it in Qt Creator's "About" window. For instance, mine says: `Based on Qt 5.4.0 (GCC 4.9.2, 64 bit)`

**Comment by jashephe** [comment]
Not the OP, but the bundled QT version does appear to be 5.4.0.  I've attached a few screenshots of what it looks like.  It's not just the menubar; the whole application is running in Low-DPI mode.

![menu](https://cloud.githubusercontent.com/assets/936132/6766247/cdfe4fae-cfd4-11e4-9618-f914baf738c4.png)
The menubar icon compared to other Hi-DPI icons.

![window](https://cloud.githubusercontent.com/assets/936132/6766250/ec1f43f8-cfd4-11e4-90b9-9ebfdff84534.png)
The application window compared to a Hi-DPI chrome window.

I attempted a hack-y fix in the style of [this suggestion](http://apple.stackexchange.com/a/69052/53142) but wasn't able to get the Info.plist flag to do anything.  I'm not too familiar with Qt; perhaps a Hi-DPI flag of some sort needs to be set there?

**Comment by ccMSC** [comment]
Ah, I thought that might be the case.

I think it needs to be enabled within the app itself - see if it's working now (v0.0.49)

**Comment by jashephe** [comment]
Sorry for the trouble, but are pre-built versions of v0.0.49 available anywhere?

**Comment by ccMSC** [comment]
Not right now, sorry. @xiy compiles them, not me

**Comment by xiy** [comment]
I'll build v0.0.49 tomorrow (GMT).

**Comment by ccMSC** [comment]
Actually I just realized I forgot to add stuff to `info.plist` - bumped the version to 0.0.50, compile that instead. Thanks :)

**Comment by xiy** [comment]
@ccMSC, @jashephe 

New release :)

https://github.com/ccMSC/ckb/releases/tag/0.0.52

**Comment by jashephe** [comment]
And indeed, that seems to do it:

![menubar](https://cloud.githubusercontent.com/assets/936132/6870607/893db5e6-d473-11e4-855c-c385e1c22bcf.png)

![window](https://cloud.githubusercontent.com/assets/936132/6870611/8c7dcb7e-d473-11e4-83e4-fafbd5898a9b.png)

I'm not the OP, so I can't close this, but it sure looks resolved to me. Cheers!
