### ISSUE TITLE
Hi all

### ISSUE THREAD

**Issue by Omerald** [ccMSC/ckb#192]
I am owner of a Corsair rgb scimitar mouse.
It's all right but playng Diablo 3 my cursor continuously tremble,
I don't know what can i do to stop it. Thanks

**Comment by a2aaron** [comment]
This probably isn't a problem with ckb. Check what DPI you've set the mouse to, what mouse pad you're using, and if mouse acceleration is turned on in your setting.

**Comment by Omerald** [comment]
in this pic you can see dpi settings of my Corsair Gaming SCIMITAR RGB MOBA/MMO Gaming Mouse .
Trembling is displayed only  when i move the mouse. When i work in desktop  also can see pointer move to the angle on the upper left. Yes I know the issue is more of one ;((
Thank you for your replay.
<img width="1548" alt="screenshot at gen 03 11-20-11" src="https://cloud.githubusercontent.com/assets/16509121/12078334/826f623c-b20d-11e5-9dae-2f572bdb45c5.png">

**Comment by Omerald** [comment]
Where can I adjust the mouse acceleration? Isystem preference or with ckb?

**Comment by a2aaron** [comment]
You can enable/disable mouse acceleration in your system preferences (you may need to look online)

**Comment by ccMSC** [comment]
Also check to make sure that your firmware is up to date and check to make sure the physical sensor is clean. I've heard that some of the Scimitars had issues like this, affecting Windows users as well. Supposedly one of the firmware updates fixed it.

**Comment by Omerald** [comment]
I am following your suggestions but unfortunately without solving any issue. 
When I am playng Diablo 3 , moving cursor the pointer tremble, only in diablo 3 !!!
I am trying to contact Blizzard assistance , maube they can help me.
Thanks for your help, I appreciate!
If I solve it I will came back here to tell you.
