### ISSUE TITLE
Unable to type a tilde on Strafe RGB

### ISSUE THREAD

**Issue by mpeechatt** [ccMSC/ckb#207]
The backquote key ` outputs a section symbol §, even though it is clearly bound to the backquote key in the ckb app.

I'm using a Corsair Strafe RGB, and I'm on OS X 10.11.2 (El Capitan).

![screen shot 2016-01-04 at 10 46 19 am](https://cloud.githubusercontent.com/assets/1315862/12097413/6eb85078-b2d0-11e5-9d6c-e48bfff33670.png)

**Comment by tatokis** [comment]
Have a look at issues #162 and #161.

**Comment by mpeechatt** [comment]
Thanks, that fixed it! Closing.
