### ISSUE TITLE
[OSX-Daemon] ckb-daemon sending Return keystroke after startup

### ISSUE THREAD

**Issue by xiy** [ccMSC/ckb#21]
**Model:** K70 RGB

Just built 20cadbe and after starting up ckb-daemon, it looks like it's stuck making the keyboard send `Return` keystrokes constantly.

**Comment by ccMSC** [comment]
Pressing enter again after starting the driver fixes it, right? I'm pretty sure it's a hardware problem. The only good way to prevent it is to run the driver at boot.

**Comment by xiy** [comment]
Seems to be okay after resetting the USB bus (plugging in a wired USB mouse)!
