### ISSUE TITLE
Start With Num Lock On

### ISSUE THREAD

**Issue by dabfalcon** [ccMSC/ckb#216]
I can't seem to find a way to make the num lock key default to enabled on boot, as opposed to disabled.

**Comment by tatokis** [comment]
If it is not built in to your operating system, have a look at the numlockx application.
Should be able to run "numlockx on" on startup.

I don't really think this is a ckb-related issue.

**Comment by dabfalcon** [comment]
I hadn't thought of it like that. You are right. 'numlockx' has resolved this. Thanks tatokis!
