### ISSUE TITLE
Strafe RGB: Wrong key on Key binding screen (Right Cmd)

### ISSUE THREAD

**Issue by shazron** [ccMSC/ckb#221]
Version:
ckb beta-v0.2.3

Keyboard:
Corsair Strafe RGB w/ latest firmware as of this date

Description:
The key `FN` on the front row (see screenshot attached, its the key to the left of the `Menu` key) is represented on the `Binding` tab as `Cmd`, and bound to `Right Cmd` by default. It is not actually bound to `Right Cmd`, a `Cmd-Spacebar` will test this (it should show the `Spotlight` searchbar in the middle of the screen, but does not)

Expected:
The key label should show up as `FN` and by default is bound to the `FN` keycode

Actual:
The key label is `Cmd` (clover key) and by default is bound to the `Right Cmd` keycode in the UI (but not actually bound to that keycode)

![screen shot 2016-01-18 at 10 01 09 am](https://cloud.githubusercontent.com/assets/36107/12398844/0512f9b0-bdcb-11e5-8536-c7be5d5320d0.png)

Strafe RGB stock keys:
![img_7722](https://cloud.githubusercontent.com/assets/36107/12399443/f722479e-bdce-11e5-8079-9a2a116b1dc1.JPG)

**Comment by SicVolo** [comment]
Fixed in pull #223. The UI is correct, but Fn keys does not seem to do much even after a proper re-bind.

**Comment by shazron** [comment]
Fixed in 0.24
