### ISSUE TITLE
Linux Mint 17 Unable to Change Colors

### ISSUE THREAD

**Issue by madmax138** [ccMSC/ckb#224]
I am running this on Mint 17.2 and when I run CKB I do not see any option to change any colors for any key. Also, when I select any of the demo profiles (e.g. rainbow) and click Save to Hardware there is no effect. 

Edit: It's also quite possible that I am just not using this correctly. But, I don't see anything related to changing the colors.

**Comment by madmax138** [comment]
Looking at other screenshots from other issues it looks like I am missing the "Lighting" tab. I only see Binding and Device.

**Comment by ccMSC** [comment]
Which keyboard do you have? If it's a regular K70 or K95 (non-RGB models), there's no way to control the lights by software, unfortunately.
