### ISSUE TITLE
BUILD.md command syntax

### ISSUE THREAD

**Issue by ntbpoh** [ccMSC/ckb#238]
In the file "BUILD.md", the line:
"Systemd (Ubuntu 15.04 and later): sudo cp -R bin/* /usr/bin && sudo cp service/systemd/ckb-daemon.service /usr/lib/systemd/system"
I think is missing a terminating "/" on the end of "system". I blindly typed this line (being a Linux noob) into terminal and it deleted the systemd/system directory, replacing it with ckb-daemon.service file renamed to "system".

**Comment by ccMSC** [comment]
Actually the correct fix is to run `mkdir -p /usr/lib/systemd/system` beforehand (`cp` won't overwrite a file with a directory but it does misinterpret the command if the directory doesn't exist). Good catch though. I fixed this in the quickinstall script a while back but apparently forgot to update `BUILD.md`.
