### ISSUE TITLE
Will this work on wayland?

### ISSUE THREAD

**Issue by Rabcor** [ccMSC/ckb#24]
I'm wondering about 4 things, do all the G-Keys work yet?, are the generic keyboard features/buttons all working? Do the volume wheel and media keys work? And will this driver work on wayland?

If it's too much of a bother to answer how far each individual keyboard has come, just answer how far the K95-RGB has come as far as features go.

**Comment by btreeinfinity** [comment]
So far everything appears to work on Fedora21/Gnome-shell/Wayland. Should work on other distros. Can you go ahead and install and test? I can help with the install if needed.

**Comment by Rabcor** [comment]
I would but I don't have the keyboard yet :p, that's why I'm asking instead of trying.

**Comment by ccMSC** [comment]
Should work just fine. You might need to install Qt5 Wayland packages but that's it.

All of the keyboard's (hardware) functions are currently supported. Options for key rebinding are a bit limited at the moment but I'm still working on them. But yes, you can use the G-keys.

**Comment by Rabcor** [comment]
Awesome, thanks :)

**Comment by Rabcor** [comment]
I just tried it on wayland, I can confirm that ckb works on wayland, but only through xwayland. If xwayland is disabled it ckb (and even ckb --background) gives a "could not connect to display" error.
