### ISSUE TITLE
Strafe RGB Corsair Logo

### ISSUE THREAD

**Issue by jonathantumulak** [ccMSC/ckb#248]
Hello,

Would it be possible to set a color for the Corsair logo on the Strafe RGB?
The app doesn't show the logo.

Thanks.

**Comment by SicVolo** [comment]
The latest version from the testing branch supports it. I've added the code to handle Strafe logo among a couple of other forgotten items.

**Comment by ccMSC** [comment]
Which version are you running? The changes should be in the main branch as of v0.2.4.

**Comment by jonathantumulak** [comment]
Im running 0.2.2. I'll check it out.

**Comment by jonathantumulak** [comment]
Thanks! Works really good.

**Comment by ccMSC** [comment]
No problem :)
