### ISSUE TITLE
Cannot turn off individual key lights

### ISSUE THREAD

**Issue by grosen** [ccMSC/ckb#25]
Using the brightness toggle (0, 33 67, 100%) only toggles the brightness for the entire keyboard. It does not impact selected keys.

Is it possible to make it select individual keys like the CUE software allows? 

Shooting for something like this

![](http://i.imgur.com/fmVZl7r.jpg)

**Comment by ccMSC** [comment]
Yes - simply set the keys' colors to black and that will turn off the lights. Be sure to exclude them from any animations as well.
