### ISSUE TITLE
[K95]How to eject my superdrive, by a key binding

### ISSUE THREAD

**Issue by joinscome** [ccMSC/ckb#250]
Hi there,

Thank you for this great application. 

I have no issue.

But I would like to be able to open and close my two DVD burners (I have a Mac Pro early 2009), using a key, like it is possible with an Apple keyboard. 
By a key binding with a function key, for example.
Is this possible ?

![12665662_10209160952361804_852265242_n](https://cloud.githubusercontent.com/assets/16600867/13140565/22915236-d633-11e5-91e6-5241aed4b18b.jpg)

**Comment by ccMSC** [comment]
The binding tab should display an option for Eject under "Keyboard > Media"

**Comment by joinscome** [comment]
Thank you for the quick answer.
This does not work for me.  I selected a key to try that , but nothing happens.

Is there any possibility to just open or close the tray ?

**Comment by frickler24** [comment]
Do you have a (shell-) command to open the tray?

**Comment by joinscome** [comment]
Yes : 

drutil tray open (or _close_ or _eject_) -drive 1 (or _2_)


The Mac Pro has two DVD burners. Number 2 is for the upper one. and number 1 si for the other (of course...).

**Comment by tatokis** [comment]
Under binding, after selecting a key, you can go under the "Program" tab, tick the "Launch program on key press" checkbox, and then enter that command in the text box below.
Should work

**Comment by joinscome** [comment]
Thank you. It works.
