### ISSUE TITLE
Fedora package list

### ISSUE THREAD

**Issue by Rabcor** [ccMSC/ckb#257]
I was installing the package to fedora and decided to make a list of what I needed to compile this time.

To compile ckb on fedora this is what is to be run before compilation: 

```
sudo dnf install zlib-devel qt5-qtbase-devel libgudev-devel libappindicator-devel systemd-devel gcc-c++
```

Please update to readme :+1: 

Also if anyone wants, a one liner for fully automatic install.

```
sudo dnf install zlib-devel qt5-qtbase-devel libgudev-devel libappindicator-devel systemd-devel gcc-c++ && wget https://github.com/ccMSC/ckb/archive/master.zip && unzip -o master.zip -d /tmp/ && rm master.zip && /tmp/ckb-master/quickinstall && rm -r /tmp/ckb-master
```

**Comment by ccMSC** [comment]
Added to the readme in the latest release (sorry...took a lot longer to get finished than I anticipated). Thanks! :)

**Comment by Rabcor** [comment]
You're welcome, and no problem, just trying to give something back ;) This is an awesome driver.

**Comment by hevanaa** [comment]
FYI there is a Fedora repository at [https://copr.fedorainfracloud.org/coprs/johanh/ckb/](https://copr.fedorainfracloud.org/coprs/johanh/ckb/) (note that it is now built on latest ckb-next)
