### ISSUE TITLE
Please Help.

### ISSUE THREAD

**Issue by BrandonGood** [ccMSC/ckb#260]
So, https://gyazo.com/b867639163e58667c1f1b5d4461058b7
This is what happens when I open the program. I can't change the lighting, I'm not trying to bind keys. I'm trying to change lighting, and there's no option for it. Can someone please help?

**Comment by ccMSC** [comment]
Unfortunately, the lighting on the non-RGB K70s isn't programmable by software.

**Comment by BrandonGood** [comment]
So I can't change the lighting at all? Thank God it came in red...

**Comment by ccMSC** [comment]
There's a button on the keyboard which allows you to program the lights - there should be instructions for doing so in your manual. But it's static lighting only (no animations) and there's no other way to change it.
