### ISSUE TITLE
K70 RGB Stops Network Connecting on Mac OS X El Capitan

### ISSUE THREAD

**Issue by dynastywind** [ccMSC/ckb#261]
I plugged my K70 RGB to my Mac OS X El Capitan, it stops the network connecting and its firmware cannot be updated via CKB (it says there is a newer version available online but cannot download and update). What's more, CKB cannot control this keyboard at all.

**Comment by ccMSC** [comment]
Do you have access to a Windows computer? If so, the best solution would be to update the firmware from there and see if that fixes the problem.

**Comment by dynastywind** [comment]
It seems that I have to get a Windows PC first...... Anyway, thank you for your advice.
