### ISSUE TITLE
[Minor Annoyance] Scandinavian keyboard is named Swedish

### ISSUE THREAD

**Issue by kimamb** [ccMSC/ckb#267]
Well, the title describes it. The scandinavian keyboard is named swedish. And as a norwegian I don't like that.

(Even the packaging states "Scandinavian" on the front)

This would be easy to fix, just change a line in the code?

![screenshot from 2016-03-05 18-07-17](https://cloud.githubusercontent.com/assets/10121762/13548990/21e78e96-e2fd-11e5-9012-f0dce401441b.png)

Only thing I could think of as a problem with the name, is that he Ø and Æ buttons are flipped around on the Danish one, and the settings don't reflect that. But the manual told me to switch the buttons around if I were norwegian.

**Comment by ccMSC** [comment]
Since the buttons are flipped I'll just make a new layout. I'll try to upload it tomorrow.

**Comment by kimamb** [comment]
Norwegian and Swedish are the same (different looks but still exact same function) Danish is the odd one. 

Sorry if you already knew this, I just thought I was that clear.

**Comment by ccMSC** [comment]
Added in ca2cb7c035a777a91d6827abe23bb6389520cc08. I put both layouts separately, in addition to the existing Swedish layout, since ckb's layouts are usually separated by country.

**Comment by kimamb** [comment]
Thanks. Everything seems to be in order.

Good job, I appreciate it.
