### ISSUE TITLE
Daemon errors on startup

### ISSUE THREAD

**Issue by RankoKohime** [ccMSC/ckb#27]
Not a critical thing, but I get errors while the daemon is starting up with my K65.  This is while running ckb-daemon as root, on an Arch Linux system.

`Corsair Keyboard RGB driver alpha-v0.0.36`
`Setting FPS to 30`
`Setting default layout: us`
`Root controller ready at /dev/input/ckb0`
`Connecting Corsair K65 RGB Gaming Keyboard (S/N: 1903001CAE3B94035375A49EF5001947)`
`Error: usbinput (profile.c:307): Operation not permitted`
`USB failure. Attempting reset (1 of 25)...`
`Error: usbinput (firmware.c:28): Operation not permitted`
`Attempting reset (2 of 25)...`
`Error: usbinput (firmware.c:28): Operation not permitted`
`Attempting reset (3 of 25)...`
`Error: usbinput (profile.c:273): Operation not permitted`
`Attempting reset (4 of 25)...`
`Error: usbinput (profile.c:307): Operation not permitted`
`Attempting reset (5 of 25)...`
`Error: usbinput (led.c:90): Operation not permitted`
`Attempting reset (6 of 25)...`
`Error: usbinput (firmware.c:28): Operation not permitted`
`Attempting reset (7 of 25)...`
`Error: usbinput (profile.c:322): Operation not permitted`
`Attempting reset (8 of 25)...`
`Error: usbinput (profile.c:307): Operation not permitted`
`Attempting reset (9 of 25)...`
`Error: usbinput (profile.c:307): Operation not permitted`
`Attempting reset (10 of 25)...`
`Error: usbinput (profile.c:322): Operation not permitted`
`Attempting reset (11 of 25)...`
`Error: usbinput (firmware.c:28): Operation not permitted`
`Attempting reset (12 of 25)...`
`Error: usbinput (profile.c:307): Operation not permitted`
`Attempting reset (13 of 25)...`
`Error: usbinput (profile.c:322): Operation not permitted`
`Attempting reset (14 of 25)...`
`Error: usbinput (profile.c:307): Operation not permitted`
`Attempting reset (15 of 25)...`
`Error: usbinput (profile.c:307): Operation not permitted`
`Attempting reset (16 of 25)...`
`Error: usbinput (profile.c:273): Operation not permitted`
`Attempting reset (17 of 25)...`
`Reset success`
`Device ready at /dev/input/ckb1`

**Comment by ccMSC** [comment]
This is normal(-ish). The keyboard hardware isn't always cooperative. The important thing is that it works eventually :)
