### ISSUE TITLE
the Option/Alt Key doesn't work at startup

### ISSUE THREAD

**Issue by Freurso** [ccMSC/ckb#272]
Found it impossible to load boot option screen by pressing the Alt Key  while only using K65 RGB.Is there something wrong with my setting? I have to use the apple wireless keyboard to enter the boot option screen.

**Comment by ccMSC** [comment]
I've had the same thing happen sometimes. Unfortunately it's an issue with Apple's BIOS (there are no drivers loaded at that point) so it's not likely to get fixed.

**Comment by Freurso** [comment]
Alright. Thank you again.

ccMSC <notifications@github.com>于2016年3月22日周二 下午2:56写道：
