### ISSUE TITLE
Keyboard configuration very limited, not able to select colours

### ISSUE THREAD

**Issue by charendoff** [ccMSC/ckb#283]
Hey, just bought a k70 and when I open up ckb, it doesn't give me an option anywhere to change the colours. I am only able to change the key bindings which I have no interest in. Is this a known issue or is it just me? If its known, when will it be fixed? And if its just a me problem how could I be able to fix it?

**Comment by charendoff** [comment]
never mind, turns out my issue was my stupidity. Turns out I bought the red backlit only. I feel like a genuine idiot.

**Comment by ZachR0** [comment]
@charendoff Cheers, my good sir :P

**Comment by ccMSC** [comment]
no worries, I should probably mention somewhere in the readme that the non-RGB versions don't have software lighting :P
