### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by will1818** [ccMSC/ckb#293]
Managed to stop the daemon but ckb process would immediately restart when I killed it, ended up using sudo kill PID; sudo rm -rf ckb.app/ which wasn't ideal. Wanted to kill because it was averaging at 60% CPU and using an insane amount of RAM. Going to reinstall now, was running the latest version.
Hope to do a clean uninstall - and then reinstall using a new binary.

**Comment by ccMSC** [comment]
`sudo rm -Rf /Applications/ckb.app` and then a reboot should be sufficient.
