### ISSUE TITLE
Taskbar problem in zorin os

### ISSUE THREAD

**Issue by Gousaid67** [ccMSC/ckb#294]
in zorin os 11, with the win 7 theme the ckb notification in the taskbar will bug it and make every element on it go off screen down

**Comment by ccMSC** [comment]
Unfortunately `QTrayIcon` has a lot of issues and there's nothing I can do about it. :/ I'd recommend using the "Hide Tray Icon" setting if you're having issues with it. You can get the window back by re-launching the app.
