### ISSUE TITLE
Ubuntu 16.04 crash

### ISSUE THREAD

**Issue by vooze** [ccMSC/ckb#308]
Hi.

First: Thank you so much for this, I even donated to show how much your work means to me!

But after switching to ubuntu 16.04 (fresh install)  ckb often crashes.

![selection_027](https://cloud.githubusercontent.com/assets/9928653/14767104/28af6684-0a1e-11e6-8792-969f3eb4727f.png)

Do you know whats going on? Are there some logs I can show you?

**Comment by ccMSC** [comment]
Somebody else reported this as well - could you provide a gdb backtrace?

Compile ckb with `./qmake-auto && make debug` and then run with `gdb bin/ckb`. When the program crashes, enter `bt full` and paste the output here.

**Comment by vooze** [comment]
Hi @ccMSC.

I found https://github.com/ccMSC/ckb/issues/296 after posting, feel a bit stupid to not search first. Anyway I did like @tatokis said. No crashes so far for 24 hours.

**Comment by ccMSC** [comment]
Okay, thanks. If it happens again please post the backtrace in #296 :)
