### ISSUE TITLE
CKB won't recognize my k95 RGB

### ISSUE THREAD

**Issue by Dumbledorf** [ccMSC/ckb#322]
I'm running 4.5.1-1-ARCH (Antergos) using GNOME Shell 3.20.1.

No matter what I do, CKB won't recognize my keyboard. I've tried different USB ports and re-installing CKB. None of it worked.

**Comment by Jeffrey-Lin** [comment]
I'm having this issue on my K70 RGB as well. I'm using Mac OS X (El Capitan).

**Comment by tatokis** [comment]
@Jeffrey-Lin You are probably having a different issue, check https://github.com/ccMSC/ckb/issues/298 out

**Comment by Dumbledorf** [comment]
Any update on this issue?

**Comment by ccMSC** [comment]
The firmware has recently been updated for the K95 as well, try the [`fw2kb`](https://github.com/ccMSC/ckb/tree/fw2kb) branch and see if you have any luck with it.

**Comment by Dumbledorf** [comment]
No luck unfortunately.

**Comment by Dumbledorf** [comment]
A few reboots fixed it for some reason.
