### ISSUE TITLE
Key Repeat Not Functioning - Corsair Strafe RGB

### ISSUE THREAD

**Issue by klaus385** [ccMSC/ckb#327]
Try changing the default writes in OS X and no go i can get i+1 repeats but no other it will not go from i to n. When n is the number of characters.

**Comment by klaus385** [comment]
This terminal command defaults write NSGlobalDomain KeyRepeat -int 0

**Comment by mhennessie** [comment]
Key repeat doesn't work on my K65 RGB either.

**Comment by klaus385** [comment]
Yeah hopefully it gets fixed its a really productivitilty killer. Don't get me wrong I'm thankful for this work! Just my only gripe.

**Comment by ccMSC** [comment]
OS X has key repeat off by default and instead uses it as a means to insert special characters. Have you disabled this setting?

**Comment by mhennessie** [comment]
@ccMSC that did the trick, thanks. For anyone else finding this here is the terminal command:

`defaults write -g ApplePressAndHoldEnabled -bool false`
