### ISSUE TITLE
Strafe RGB Not Detected 0.2.5

### ISSUE THREAD

**Issue by jameskrawczyk** [ccMSC/ckb#332]
The Strafe RGB isn't detected running 0.2.5. I tried all the trouble shooting items, tried initialising the daemon manually, and loading/unloading the LaunchDaemon. I also tried switching the keyboard around in BIOS mode. 

The only thing that finally worked was reverting to v0.2.4 where it works flawlessly.

I had a look at the logs when it wasn't working and it would cycle through something like ifhid[0], ifhid[1] ... etc then just hang. If I get a chance and you need it I'll reinstall 0.2.5 and pull the exact log message.

OSX 10.11.4

**Comment by ccMSC** [comment]
Sorry for never replying to this earlier. I *think* I've got the issue sorted out in v0.2.6, based on some other people's testing. There were a couple of different threads like this so I'm going to close them, but please do open a new issue if the problem still happens.
