### ISSUE TITLE
after firmware 2.04 update on Corsair K70rgb - CKB  failed 

### ISSUE THREAD

**Issue by Hal1102** [ccMSC/ckb#336]
I upgraded firmware on Corsair K70rgb and ckb v0.2.5 does not work anymore ,
I uninstalled ckb and the keyboard works in basic mode ,( led in white mode ) ,
what to do ?

**Comment by tatokis** [comment]
There is a fix for this issue in the fw2kb branch. Have a look at issue #298

**Comment by Hal1102** [comment]
the new firmware K70rgb is 2.04 not 1.33 
issue #298 
it's old

**Comment by mhennessie** [comment]
@Hal1102 building and installing CKB from the fw2kb branch works fine with K65/70/95 RGB keyboards running the 2.04 firmware.

**Comment by Hal1102** [comment]
eureka !
with "fw2kb"   https://github.com/ccMSC/ckb/tree/fw2kb
I solved the problem !!
many thanks @mhennessie 
the next
