### ISSUE TITLE
OS X 10.11.4 K65 Not working

### ISSUE THREAD

**Issue by anthonycastelli** [ccMSC/ckb#341]
I just installed all of this and even tried compiling it myself but have had no luck getting my keyboard to work. I've updated to the latest version (2.04) and its still not working. Is that firmware too new for this? I'm tried a bunch of stuff and can't seem to get it to work. Any help is greatly appreciated!

**Comment by tatokis** [comment]
If you are running firmware 2.04, make sure to compile the fw2kb branch instead.

**Comment by anthonycastelli** [comment]
I have tried that and still no luck.

**Comment by tatokis** [comment]
Do you happen to have a K65 Lux RGB? (#320)

**Comment by anthonycastelli** [comment]
No, its the K65 RGB, the regular one I guess.

**Comment by anthonycastelli** [comment]
Still no luck with the keyboard. I don't even get it to recognize it. Ive tried a few things but no dice. Any other ideas?

**Comment by ccMSC** [comment]
Hi, there have been a lot of threads about new devices and I don't want to divide attention between all of them. I've opened up a new thread for them all: #386 - Please continue discussion there, thanks!
