### ISSUE TITLE
Corsair K65 RGB Rapidfire not being recognized

### ISSUE THREAD

**Issue by rbieb** [ccMSC/ckb#344]
Ckb says

    No devices connected

Tested the fw2kb branch too, but the issue stays the same. This is on linux btw.

I already saw that the rapidfire isn't being supported yet, but I suppose opening an issue could channel all the info towards getting it to work in one place.

**Comment by newnewcorsair** [comment]
same here. Using on Mac 10.11.4

**Comment by edman545** [comment]
Not working on xubuntu 15.10 here.

**Comment by Kithop** [comment]
Yeah, I pulled a USB packet capture on my K70 Rapidfire in #319 , from under Windows with the CUE software running.  Suggest you guys follow that one, or if anyone wants to try their hand at reading it as I'm not a dev... :)

**Comment by ccMSC** [comment]
Hi, there have been a lot of threads about new devices and I don't want to divide attention between all of them. I've opened up a new thread for them all: #386 - Please continue discussion there, thanks!
