### ISSUE TITLE
Corsair Strafe RGB Not Working Firmware 2.04 HELP

### ISSUE THREAD

**Issue by Atlantian0424** [ccMSC/ckb#347]
Once I upgraded to the 2.04 firmware CKB stopped working so could someone explain how to download the update for the mac driver please?

**Comment by tatokis** [comment]
https://github.com/ccMSC/ckb/issues/298#issuecomment-218058262

**Comment by Praethiax** [comment]
I have the same problem. I reinstalled everything and tried to compile it manually.
Didn't work for me.  But i'm no expert. So maby i did it wrong.
I'm on Linux Mint btw.

**Comment by Praethiax** [comment]
https://github.com/ccMSC/ckb/tree/fw2kb
This worked for me. Don't know that's difference. I don't know whats a branch, Fork..
I don't know how github works
I know nothing. But i'm happy now
