### ISSUE TITLE
Need the Older Firmware Because New One Is Incompatible

### ISSUE THREAD

**Issue by Venacity** [ccMSC/ckb#351]
I was kind of a knob and updated firmware through my friend's Dell laptop. Now my firmware is incompatible with CKB. Does someone have the Strafe RGB firmware that is old enough to work with CKB because I haven't been able to find it online. Thanks in advance!

**Comment by light2yellow** [comment]
Just compile from fw2kb branch, it contains fixes for 2.04 firmware version.

**Comment by Venacity** [comment]
I'm not sure how to do that, but I got Corsair Support to help me downgrade the firmware. However CKB is still not detecting the keyboard.
