### ISSUE TITLE
No recent ckb version will recognize my k65. Im running el capitan 10.11.4 any troubleshooting advice. I have already rebooted my computer a few times and tried multiple usb ports (all 3.0)

### ISSUE THREAD

**Issue by zambo51** [ccMSC/ckb#352]

**Comment by light2yellow** [comment]
Try to compile from fw2kb branch and write back.

**Comment by mhennessie** [comment]
Do you have the new K65 RGB Lux or the older non Lux version? 

If you have the older one then I assume you updated the firmware to 2.0.4, in which case you will need to compile the fw2kb branch as stated above and then it should work fine. I am currently running OS X 10.11.5 with a K65 RGB non-Lux with firmware 2.0.4 using the fw2kb branch and it works perfect.

**Comment by ccMSC** [comment]
I'm assuming it's the Lux. I opened up a new thread for them: #386 

If it's not the lux then v0.2.6 should support it.
