### ISSUE TITLE
M65 PRO RGB compatible w/ ckb v0.2.5?

### ISSUE THREAD

**Issue by WifiTrash** [ccMSC/ckb#361]
I am planning on upgrading my current mouse to a Corsair M65 PRO, and am wondering if that is compatible with ckb v0.2.5 (w/ logging enabled).

**Comment by lukeberry99** [comment]
I have the Corsair M65 Pro, and it isn't detected by the software (currently)

**Comment by CorreAktor** [comment]
I too have the M65 Pro and it doesn't work currently, as well as the K70 Rapid-fire RGB.

**Comment by ccMSC** [comment]
Hi, there have been a lot of threads about new devices and I don't want to divide attention between all of them. I've opened up a new thread for them all: #386 - Please continue discussion there, thanks!
