### ISSUE TITLE
Keyboard dies after firmware update in windows

### ISSUE THREAD

**Issue by Kira9204** [ccMSC/ckb#364]
Hi!
I bought a K70 RGB today, plugged it in and installed the software on Ubuntu 16.04.
Everything worked perfectly fine until i later during the day updated the firmware in windows. 
Now the keyboard ignores all options and dies completely if i try to apply any animation.

**Comment by tatokis** [comment]
Compile and install the fw2kb branch

**Comment by Kira9204** [comment]
I removed and reinstalled with that branch but the issue persists.

**Comment by Kira9204** [comment]
Everything works perfectly again!
Thank you!

**Comment by ryanaltvater** [comment]
Same exact issue, and will try compiling that branch.

**Comment by ryanaltvater** [comment]
I compiled the fw2kb branch, replaced the existing CKB.app, and I'm still experiencing the same issue. My keyboard is lighting up with the base colors of my profile but it's not triggering the animations and my keyboard is pretty much unresponsive. Pressing "asd" = "l;'" on my K70 RGB keyboard. This mess started happening after I updated the Windows firmware yesterday on my desktop (big mistake, as I use my MacBook and K70 for work).

**Comment by ryanaltvater** [comment]
Also, I can't seem to load the demo profile or reset the keyboard either.

**Comment by t3kg33k** [comment]
I've run into the same issue. Firmware updated within Windows, rebooted back into Ubuntu Mate 15.10, and my K65 keyboard no longer works. It looks as if the ckb-daemon crashes. I attempt to start the daemon, it runs for short time and then crashes again.

**Comment by ryanaltvater** [comment]
@t3kg33k After contacting Corsair support, I ended up rolling the Windows CUE software (v1.15.36) and keyboard firmware (v1.30) back and it fixed everything for me.

**Comment by t3kg33k** [comment]
@ryanaltvater Thanks. I'll try that tonight.
Corsair bastards need to include Linux drivers.

**Comment by ryanaltvater** [comment]
@ccMSC how come you closed this issue? Did you release a fix?

**Comment by ccMSC** [comment]
Yes, v0.2.6 is compatible with the latest firmware.
