### ISSUE TITLE
mac user problem

### ISSUE THREAD

**Issue by dreamcog** [ccMSC/ckb#365]
I have three problems when i use ckb in mac os.

1) if I switch the button behind the keyboard k70. from BIOS to 8 or other key, The CKB shows : " no devices connect." and I cannot get the colorful light.

2) if I switch the button to BIOS, and the modifier software Karabiner cannot modifier the different keys from mac os. I wanna modifier (Win,Alt) to (Option,Command), and modifer F4 key become application key.

3)when I use BIOS mode , and the keyboard shows the colorful light, when i press anykey in Keyboard, the light brightness will changes , press One key will reduce 33%,  After 3 Keys press the light will off,and when I press the fourth key, the light will turn on again. It's very strange。

Thanks for Answer, If there is anything i am not write will clearly please let me know.
Sorry, I am not from a english speaking country.

**Comment by tatokis** [comment]
Which K70 do you have? RGB or RGB Rapidfire?
And if so, what firmware version is it running?

If you have a K70 RGB and it runs firmware version 2.04, then you need to compile ckb from the fw2kb branch. Alternatively, someone has provided a package that you can try to install, in https://github.com/ccMSC/ckb/issues/298#issuecomment-218058262

If you have a K70 RGB Rapidfire, then unfortunately, it is not supported.

**Comment by EmeraldGamer** [comment]
Wait rapid fire is not supported
will it be supported in the near future?

**Comment by dreamcog** [comment]
thanks tatokis,
but it's doesn't work with my keyboard.

My keyboard is K70 RGB, and with firmware v2.04.
Use Mac OS X 10.11.5

I just uninstall the CKB, and the keyboard works, can type any letter as it before.
I am waiting for CKB could update for completely solve the problems:)

**Comment by tatokis** [comment]
@dreamcog Install XCode and Qt as mentioned here:
https://github.com/ccMSC/ckb#building-from-source
then download the source code from https://github.com/ccMSC/ckb/archive/fw2kb.zip
and finally run quickinstall from it.

That should compile CKB with the fixes for firmware 2.04, if that doesn't work, then unfortunately I can't help as I do not have a Mac.

**Comment by dreamcog** [comment]
@tatokis Thanks a lot tatokis ,I will try it tomorrow, Now it's very late in china:)
hope it works. I will reply to you after i try.thanks

**Comment by tatokis** [comment]
No worries, I forgot about it completely, but there is another build as 
mentioned in 
https://github.com/ccMSC/ckb/issues/298#issuecomment-223824964 , so you 
might want to try that one first.

**Comment by dreamcog** [comment]
@tatokis I tried it this morning.and still a problem here : [https://github.com/ccMSC/ckb/issues/298#issuecomment-223824964](url)

**Comment by dreamcog** [comment]
@tatokis I tried it this morning.and still a problem here : https://github.com/ccMSC/ckb/issues/298#issuecomment-223824964

**Comment by mhennessie** [comment]
I had to build my own for the K65 RGB on OS X running 2.0.4. The one pre compiled [here](https://github.com/ccMSC/ckb/issues/298#issuecomment-216055305) by @4t0m1k didn't work for me either. After installing QT I was able to do it in a few mins.
