### ISSUE TITLE
OSX M65 Support

### ISSUE THREAD

**Issue by lukeberry99** [ccMSC/ckb#371]
I've just picked up an M65 Pro and noticed that ckb currently doesn't support it, is there any plans for M65 Pro support? What can I do to help?

**Comment by CorreAktor** [comment]
+1 on M65 Pro support. Just got this mouse and the K70 Rapidfire RGB. Both are great and it would be awesome if they could work on the Mac. I second, anything I can do to help, test, etc.?

**Comment by ccMSC** [comment]
Hi, there have been a lot of threads about new devices and I don't want to divide attention between all of them. I've opened up a new thread for them all: #386 - Please continue discussion there, thanks!
