### ISSUE TITLE
./quickinstall: line 200: 19598 Aborted

### ISSUE THREAD

**Issue by haydenjames** [ccMSC/ckb#373]
Fresh install of:
Kubuntu 16.04 LTS

With:
K65 lux

Quick install gives this error after 'Start ckb now [Y/n]? Y':
`./quickinstall: line 200: 19598 Aborted                 (core dumped) $APP --close > /dev/null 2>&1`

**Comment by tatokis** [comment]
That happens because the daemon crashes as your keyboard is not supported.

**Comment by haydenjames** [comment]
Ahh! K65 **LUX** RGB not supported you are saying? I will exchange it at BestBuy for the regular "K65 RGB".

**Comment by tatokis** [comment]
Yeah, see https://github.com/ccMSC/ckb/issues/320
Also, might want to try the fw2kb branch, as it contains fixes for the new firmware (2.04).

**Comment by tatokis** [comment]
However, since there was a crash, please try running ckb with the K65 unplugged, to see if it will start successfully or not.
If it doesn't start, there is chance that you came across another issue as well.

**Comment by haydenjames** [comment]
Thank! I picked up the regular k65. This works perfectly!
