### ISSUE TITLE
CKB fails to detect Corsair Sabre RGB/No devices connected

### ISSUE THREAD

**Issue by nbulischeck** [ccMSC/ckb#377]
Linux box 4.6.2-1-ARCH #1 SMP PREEMPT Wed Jun 8 08:40:59 CEST 2016 x86_64 GNU/Linux

I can use the device just fine, but ckb never picks it up. Forever "No devices connected". I've tried every conceivable combination of the quirks, even the 0x4 suggestion and nothing worked. The CKB daemon is 100% enabled and running.

Terminal output is: hid-generic 0003:1B1C:1B2F.0002: usb_submit_urb(ctrl) failed: -1

**Comment by ccMSC** [comment]
Should be fixed by the new version release. Issue with the new firmware.

**Comment by nbulischeck** [comment]
New version release of ckb? Or of the firmware?

**Comment by ccMSC** [comment]
new version of ckb: https://github.com/ccMSC/ckb/releases/tag/v0.2.6

**Comment by nbulischeck** [comment]
Still no luck getting it to recognize the device.

**Comment by SethBarberee** [comment]
I have a Strafe RGB with the newest firmware and it is detected properly. I kept the USB quirks in my kernel to avoid that error above. In the end, it works great for me!

**Comment by nbulischeck** [comment]
Not sure what to tell you because it still doesn't work for me =/

**Comment by ccMSC** [comment]
You probably have the newer sabre model. Try compiling this branch and see if it works: https://github.com/ccMSC/ckb/tree/newdev

If not, please see #311

**Comment by nbulischeck** [comment]
It worked! Thanks for your help.

**Comment by sabrehelp** [comment]
Hi, I am now having this same issue. Sorry if its a silly question but how do I "Compile" the above branch? 
Thanks for your time!

**Comment by frickler24** [comment]
@sabrehelp please have a look at the more recent fork by [mattanger/ckb-next](https://github.com/mattanger/ckb-next).

**Comment by sabrehelp** [comment]
I keep getting a "you cannot open the application because it is damaged or incomplete" after quick install. @frickler24
