### ISSUE TITLE
Can't Get Ckb Working on Linux Deepin

### ISSUE THREAD

**Issue by dabfalcon** [ccMSC/ckb#380]
Linux Deepin is Debian-based nowdays. I can install Ckb on the OS from GitHub but can't get it to actually change any colours. What can I do to help troubleshoot this issue?

**Comment by ccMSC** [comment]
What specifically is the problem? Does the GUI show the keyboard but you're unable to change anything, or are you getting the `Driver inactive` or `No devices connected` screen?

**Comment by dabfalcon** [comment]
The former happens. I believe the keyboard even stopped working, as well. I'm now on another computer using Deepin and facing the same problem. Its probably trouble with dependencies. apt-cache search qt5 gives like 1 million results but apt-get install qt5 doesn't work. What should I try?

**Comment by tatokis** [comment]
Considering you already got ckb compiled, I don't think it is a Qt issue, as that only affects the GUI and not the daemon.

Have you added the correct quirk parameters to GRUB?

Which device do you have?
Some of the new devices require code which exists on the "newdev" branch.

**Comment by dabfalcon** [comment]
Issue resolved. For some reason I'm worked on this install. Maybe Ckb caught up to the firmware I was running? In any-case, re-ran quickinstall fixing errors by downloading appropriate packages. USB Quirk and is all good. Thanks

**Comment by ccMSC** [comment]
It's possible; the latest firmware was incompatible with the master branch for quite a while. Glad you got it working though.
