### ISSUE TITLE
Can CKB load .mode or .prf file?

### ISSUE THREAD

**Issue by sunjingbang** [ccMSC/ckb#382]
Got lots .mode/.prf files on Windows, can CKB support load those files in the future?

**Comment by ccMSC** [comment]
No, this has been a requested feature for a long time but unfortunately I've had to deal with a lot of bugs/firmware issues so I've never gotten around to it. However I'm definitely going to try and implement this within the next 1-2 months.

**Comment by sunjingbang** [comment]
Thanks, take ur time and I'll wait for the good news.
