### ISSUE TITLE
I'm using macOS sierra and K65 RGB RAPIDFIRE  

### ISSUE THREAD

**Issue by mrgaolei** [ccMSC/ckb#383]
There's no any effect with ckb.
Any setting has no effect.
It seems is a UI only, can't bind key, can't control LED.
Why?

**Comment by tatokis** [comment]
Rapidfire is not yet supported.

**Comment by mrgaolei** [comment]
Is there any plan to support Rapidfire?

**Comment by tatokis** [comment]
The main dev said they will look into supporting the series of new 
keyboards, so probably at some point in the future.

**Comment by ccMSC** [comment]
Yep, opened a new branch/thread for them new: #386
