### ISSUE TITLE
K65 LUX RGB not detecting with ckb 0.2.6

### ISSUE THREAD

**Issue by MdsCool** [ccMSC/ckb#385]
Pretty much title.
Not detecting the keyboard.

**Comment by tatokis** [comment]
The Lux is not supported

**Comment by MdsCool** [comment]
Do you think it will be supported any time soon?

**Comment by macdaddy39** [comment]
Same issue please, neither of my devices are supported apparently:

K65 LUX RGB    &     M65 PRO RGB

Please consider including these products as they are the most recent line of products from Corsair. 

They models are readily available at Best Buy and TigerDirect... many people are buying them.

**Comment by tatokis** [comment]
#386

**Comment by ccMSC** [comment]
I'm closing all other threads for this right now. Please try out the branch linked in #386 and let me know if it's working :)
