### ISSUE TITLE
Keyboard Firmware 2.05

### ISSUE THREAD

**Issue by Serubin** [ccMSC/ckb#396]
Is the fw2kb branch working with the 2.05 firmware?

**Comment by tatokis** [comment]
I was not aware there was a 2.05 version, however I just upgraded my K70 RGB to 2.05 manually using ckb and the bin file from the FIRMWARE file.

I can confirm that the K70 RGB works fine with ckb and 2.05 on linux.
![2c51d3cb03df](https://cloud.githubusercontent.com/assets/6003656/16290171/da9fdc66-3903-11e6-9326-18c626bfd875.jpg)
![c2d2b1e0a6c9](https://cloud.githubusercontent.com/assets/6003656/16290174/e03f0944-3903-11e6-9c44-2d222e0206a3.jpg)

**Comment by Serubin** [comment]
Thank you for taking that risk for me :)
