### ISSUE TITLE
new firmware k70rgb 2.05 ( which ckb install )

### ISSUE THREAD

**Issue by Hal1102** [ccMSC/ckb#400]
it seems that ckb beta-v0.2.5+f04 no longer functions well with firmware 2.5 Corsair
( in linux Ubuntu 16.04 )
I asked myself what was the right version of ckb for this new firmware 2.05 
could you give me a hint ?

**Comment by ccMSC** [comment]
beta-v0.2.6 is compatible with the v2.05 firmware.

**Comment by Hal1102** [comment]
many thanks
