### ISSUE TITLE
 No devices connected with the latest version [K70 LUX RGB]

### ISSUE THREAD

**Issue by singleseeker** [ccMSC/ckb#406]
Still shows me No devices connected with ckb beta-v0.26+d01.
I use  K70 LUX rgb.

**Comment by colinazzam** [comment]
I am having the same issue. I'd be more than happy to provide any information or assistance that could help get this keyboard to work.

**Comment by xiangyad** [comment]
Made it work by adding the hardware ID to some of the scripts here. More than happy to share the pkg.

**Comment by xiangyad** [comment]
[ckb.zip](https://github.com/ccMSC/ckb/files/349212/ckb.zip)

**Comment by ChiefPaleface** [comment]
I was having the same issues on Ubuntu for the k95 RGB. Not sure why but a reinstall did the trick.

**Comment by tatokis** [comment]
The K70 Lux doesn't work because there wasn't support for it in the code.
It was added some time ago, and you need to build and install ckb from here https://github.com/ccMSC/ckb/archive/newdev.zip

**Comment by stevenkendrick3** [comment]
Hey. I really hope that someone will respond to this. I recently bought a K70 LUX RGB keyboard. I am having the same problem where it says no devices connected. It seems like you solved the problem. I am just to stupid to understand how to fix it... I am by no means a programer so I was hoping that one of you could walk me through how to fix this? @tatokis  @singleseeker  @colinazzam  @xiangyad @ChiefPaleface

**Comment by slugger7** [comment]
@xiangyad i would like to know what you did to fix the problem if that will be possible.

**Comment by stripTM** [comment]
Hi, I have the K70 Lux (no RGB).

I have connected it to windows and I have updated the firmware.

I added in the kernel cmdline usbhid.quirks=0x1B1C: 0x1B09: 0x0x20000408 and restart

I installed the version of @tatokis ckb beta-v0.2.6 + d01

And I still can not get the message "No devices connected"

This is what I get if I execute **lsusb -d 1b1c: 1b36** show:
Bus 001 Device 003: Corsair ID 1b1c: 1b36

I would also like to know what is wrong, if you could at least orient me in the code that I have to find / add / change.

**Comment by bigdan4712** [comment]
@tatokis YOU ARE THE MAN!

**Comment by raviv** [comment]
@tatokis - Thanks !

**Comment by tatokis** [comment]
For anyone possibly stumbling across this, update to https://github.com/ckb-next/ckb-next

**Comment by AntonisHopkins** [comment]
@tatokis  good job man

**Comment by riprip74** [comment]
Thx, installing ckb-next as mentionned above did the trick!
