### ISSUE TITLE
Upgrading ckb-daemon

### ISSUE THREAD

**Issue by BlakeCalhoun15** [ccMSC/ckb#429]
my cab software says that I have a "driver version mismatch (beta-v0.2.5)" and it says I need to upgrade my ckb-daemon,but how do I go about doing this?

**Comment by BlakeCalhoun15** [comment]
okay i restarted my computer and it doesn't show that message anymore. it now doesn't recognize my keyboard at all

**Comment by fleischie** [comment]
Hey@BlakeCalhoun15 

What OS are you running the software on? How did you install `ckb`? What keyboard do you have?

I hope you are still interested in fixing this issue after all that time. 😄
