### ISSUE TITLE
Volume wheel not working

### ISSUE THREAD

**Issue by grosen** [ccMSC/ckb#46]
The volume wheel no longer controls volume output. Occasionally on first volume wheel scroll it will show the volume dialog for a second and then disappear and fail to do anything.

**Comment by ccMSC** [comment]
Fixed in 7a9dedeb8c156dd5eab01183105da9eb58411cab. You may have to restart your computer if you have the previous version running.

**Comment by grosen** [comment]
Fixed thanks!
