### ISSUE TITLE
Modifier keys not available in Steam games

### ISSUE THREAD

**Issue by augustf** [ccMSC/ckb#47]
It may be other heavyweight fullscreen applications as well, but when I'm inside Steam, the ctrl, alt, and shift keys are unavailable. At first, I thought ckb had quit, but other keys that would not work if it had (like Escape and the number keys) work fine. I've no idea why it's just these keys/

**Comment by ccMSC** [comment]
I wasn't able to replicate this issue (at least not in Source games) but it probably has to do with modifier keys having a different event type. See if 2979e17db82792493dcc1335105c05902744d904 fixes it.

**Comment by fliiiix** [comment]
Which game?

**Comment by augustf** [comment]
@fliiiix I was playing Grand Theft Auto Vice City on OS X Steam.

**Comment by augustf** [comment]
The latest version worked for me -- all seems well.
