### ISSUE TITLE
compile failed on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by mrgaolei** [ccMSC/ckb#470]
```
./os.h:72:13: error: typedef redefinition with different types ('int' vs
      'enum clockid_t')
typedef int clockid_t;
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:171:3: note:
      previous definition is here
} clockid_t;
  ^
1 warning and 1 error generated.
make[2]: *** [debug/device.o] Error 1
make[1]: *** [debug] Error 2
make: *** [sub-src-ckb-daemon-make_first] Error 2
```

I'm using qt 5.7 and K65 RGB RAPIDFIRE

**Comment by horen20wash** [comment]
Please comment out 

line 72
typedef int clockid_t  in src/ckb-daemon/os.h 

It will compile without problems.

**Comment by mrgaolei** [comment]
@horen20wash when I do it, compile pass.
But in ckb.app show `No devices connected`
My Device id is: `0x1b39`
How do I debug what's wrong with me?

**Comment by horen20wash** [comment]
Are you compiling the checkout from the newdev branch, right ? 

It has the right entry
#define P_K65_RFIRE     0x1b39
#define P_K65_RFIRE_STR "1b39"

You also followed the steps to install "service/launchd/com.ckb.daemon.plist" to "/Library/LaunchDaemons"

**Comment by mrgaolei** [comment]
OK, I got it.

**Comment by mrgaolei** [comment]
I forget to launchctl, thanks, It works fine.
