### ISSUE TITLE
Selecting multiple items with the shift key does not work

### ISSUE THREAD

**Issue by rohitmucherla** [ccMSC/ckb#475]
Hi, 

When I try to select multiple items, i.e. multiple emails by using the shift key and clicking, it doesn't do that like the apple keyboard on my MacBook pro. I can't seem to pinpoint a reason for this since the binding is the default and nothing has changed otherwise. 

Thank you very much for your time!
--
Computer: 2015 15" Retina MacBook Pro
Keyboard: Corsair Strafe  RGB

**Comment by BrekiTomasson** [comment]
Collecting this and other Sierra-related issues in #473

**Comment by rohitmucherla** [comment]
Thank you very much sir. I'm closing this one then.
