### ISSUE TITLE
Keyboard needs a long time to "boot" and start working, sometimes it kicks other USB Devices

### ISSUE THREAD

**Issue by guenniman** [ccMSC/ckb#476]
Strafe RGB on Linux Mint 18 (4.4.0-21-generic) ckb version: beta-v0.2.6

Whenever I plug the Keyboard into my computer it takes 20 seconds to 2 minutes for the keyboard to start working. And sometimes when I plug the keyboard in my mouse and headset stop working.

**Comment by tatokis** [comment]
Find the dev id of your keyboard and add the appropriate quirk for it, 
as per the readme.
