### ISSUE TITLE
Please, add the spanish layout! ;)

### ISSUE THREAD

**Issue by bhean** [ccMSC/ckb#48]
It isn't an issue, it's just an appeal hehehe...
Please, add the spanish layout to the project,

Thank you in advance!

**Comment by ccMSC** [comment]
Done! check out ecfa82d24cb11d0910c87c29ffdd2ce84089869b - be sure to upgrade the driver first :)

**Comment by bhean** [comment]
Great! Thank you very much! And thank you for the fast reply!

Regards from Spain,
