### ISSUE TITLE
Shift and Cmd-select not working on OS X Sierra

### ISSUE THREAD

**Issue by augustf** [ccMSC/ckb#483]
On OS X Sierra with a K70 RGB Keyboard, I'm not able to select items singly (using Command-click) or as a group (Shift-Click). This only began after my upgrade and is not replicated on my Bluetooth keyboard, which works fine. I upgraded to the latest ckb app and installed the latest firmware, but nothing helped. I've unplugged the keyboard and rebooted, cleaned caches, repaired permissions, and a few other steps.

Has anyone else had this issue?

**Comment by mhennessie** [comment]
Already noted in issue #473

**Comment by mhennessie** [comment]
And #472

**Comment by augustf** [comment]
Ahh - those escaped my search. Thanks! I'll follow them closely.
