### ISSUE TITLE
Modifier keys override: Add Caps lock - > Escape

### ISSUE THREAD

**Issue by eddie-dunn** [ccMSC/ckb#49]
As an ardent Vim user I be grateful if you could add an override for the Caps Lock key to bind it to Escape instead.

**Comment by ccMSC** [comment]
You can do this from the binding tab. Click on the Caps Lock key to modify it, Esc is the first option under "Function / Misc": ![](https://i.imgur.com/e2qFMkj.png)

**Comment by eddie-dunn** [comment]
Ah, OK, thanks. I was looking inside the Settings tab for some reason.

Great work btw! Corsair should hire you. Expect a donation coming your way soon. :)
