### ISSUE TITLE
Mac OS X- Menubar Icon Cannot be moved

### ISSUE THREAD

**Issue by c010rb1indusa** [ccMSC/ckb#53]
The menubar icon for ckb.app cannot be moved with command+drag like normal menubar items. It doesn't show up in third party applications that manipulate menubar items either like 'Bartender'.

I'm running the software as a service.

**Comment by ccMSC** [comment]
There's probably nothing I can do about it since the tray icon is a Qt class and I don't see any documentation about this. I'll keep the issue open in case anyone knows of a solution, though.

**Comment by cocotutch** [comment]
Custom OS X Menulets cannot be moved. The Apple ones are a PrivateAPI and despite being an active OS X and iOS Developer for 10 years, have not yet found a public way to allow this behaviour.

This issue can be closed. :)

**Comment by ccMSC** [comment]
Figured it was something like that. Shame. Thanks for sharing.
