### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by dkuida** [ccMSC/ckb#574]
I consider creating the support for that, but before I start wanted to make sure if there is a magor blocker for that to work ? besides the tie needed I mean

**Comment by frickler24** [comment]
@dkuida Have you already seen the site [from mattanger](https://github.com/mattanger/ckb-next)?
Help is appreciated in many points - support, implementation, debugging, test and so on.
That fork is 8 months in front of this one from ccMSC.

**Comment by dkuida** [comment]
thanks
