### ISSUE TITLE
Error when downloading firmware.

### ISSUE THREAD

**Issue by penetal** [ccMSC/ckb#58]
Linux: 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64 GNU/Linux
CKB: beta-v.0.1.3
Current firmware: 1.13

When I try to update firmware version on the keyboard it says:
> There was a problem with the downloaded file.
> Please try again later.

Using the information in the FIRMWARE file I downloaded the firmware, unzipped and checked the bin against the SHA256, it matched.

**Comment by grosen** [comment]
Same

**Comment by ccMSC** [comment]
I wrote the wrong thing in the file name column...oops! fixed now.

**Comment by penetal** [comment]
I can now download firmware with the tool, updated firmware as well, all seems to work for me.
