### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by jennydaman** [ccMSC/ckb#584]
cdk-daemon would sometimes use 100% of a logical CPU constantly. It would seem to happen after I have used my computer for a while, maybe it happens when I wake my computer from suspend. This has happened multiple times, though I can't replicate the issue. If I find out what is causing the issue, I'll update this post. 
If anyone else is having a similar issue, it can be easily fixed by:
`sudo systemctl restart ckb-daemon`

Probably unnecessary information: 
ckb beta-v0.2.6
Corsair STRAFE (non-RGB)
Antergos Linux (x86_64 Linux 4.9.11-1-ARCH)

**Comment by byinarie** [comment]
Just letting you know there is a new fork for this project :) https://github.com/mattanger/ckb-next

also see: https://github.com/mattanger/ckb-next#what-happened-to-the-original-ckb
