### ISSUE TITLE
MM800 RGB Mouse Pad Polaris Support

### ISSUE THREAD

**Issue by Dygear** [ccMSC/ckb#585]
Please add MM800 support.

http://www.corsair.com/en-us/landing/polaris

**Comment by byinarie** [comment]
Just letting you know there is a new fork for this project :) https://github.com/mattanger/ckb-next

also see: https://github.com/mattanger/ckb-next#what-happened-to-the-original-ckb

**Comment by Dygear** [comment]
@byinarie, I'm running ckb-next-latest-git  v0.2.4.r193.g7a13207-1 from you now. As I use Arch Linux. Still no joy with that version. I shall close this and update over there (as needed).
