### ISSUE TITLE
Missing one button in typing menu

### ISSUE THREAD

**Issue by Rabcor** [ccMSC/ckb#59]
There is a button on EU keyboards for "<", ">" and "|", I don't know what it's called but I have US keyboard layout which doesn't physically have this button. I want to be able to map it to some key I never use (like the menu key or win lock key or something) but it's not in the menu.

When I use the US keyboard layout on an EU keyboard this button does function the same way except it is missing the "|" function (default press is <, shift press is >)

According to Xev, this button is called **less** and it's keycode is **94**, it's keysym is **0x3c**.

**Comment by ccMSC** [comment]
At the moment the GUI only supports keys that are on the physical keyboard - support for additional keys is planned soon. I think you could simulate it by running `xdotool key` as a custom program, though.

**Comment by Rabcor** [comment]
For now I'm solving it by setting it to another language in the GUI which does have this key (I think I'm using the swedish setting) seems to be working fine that way. although it perhaps isn't pretty.

**Comment by ccMSC** [comment]
As of 9d2784dc8109724ce121d0cf497fc5ad9232d41f you should be able to assign the extra ISO key even with a US layout.
