### ISSUE TITLE
Corsair Keyboard on Mac OSX Sierra only work on alphabets

### ISSUE THREAD

**Issue by birdieman** [ccMSC/ckb#591]
#Plug in my Corsair K95 Platinum, and then go to System Preference > Keyboard > Modifier and change Control and Command Key. Restart computer but still only the letters and numbers are working. Any symbols or delete (backspace) button are unresponsive. 

This is my first time in here so I have never install any CKB related materials. I would assume at least the keyboard itself will function properly except the command key and the RGB will not function at all. But none of the symbols key works. So can someone points me in the right direction? Thanks.

I am using my 2008 Mac Pro on different USB (2.0) port and on Change Keyboard Type, it has no response when I hit the left key next to the right Shift key.
I then plug the keyboard to my 2013 MBP USB (3.0) port, at least the Change Keyboard Type works, and the delete button works.  Wonder why...

**Comment by frickler24** [comment]
@birdieman please have a look at the [newer fork](https://github.com/mattanger/ckb-next) and look at the issues. I'm not the mac-guru, but I think your topic is addressed yet.
