### ISSUE TITLE
K70 LUX RGB

### ISSUE THREAD

**Issue by siojima** [ccMSC/ckb#595]
Just recently purchased this great keyboard, had everything plugged in, but the ckb.app doesn't recognise it. I used the latest version of the OS X 

Any insights into the cause of the problem or when a patch/update may be coming?

**Comment by frickler24** [comment]
Did you [try this fork](https://github.com/mattanger/ckb-next)? For K70 Lux RGB please use branch testing, because yesterday was an update for this KB.
