### ISSUE TITLE
No devices connected for Sabre RGB

### ISSUE THREAD

**Issue by LeonBlade** [ccMSC/ckb#605]
Downloaded the `sabre` branch in hopes that it would be detected but it doesn't look like it is.

**OS:** macOS 10.12.6
**Mouse:** Corsair Sabre RGB [CH-9303011-NA]

**Comment by ElSoEasY** [comment]
Same problem

**Comment by alejzeis** [comment]
Try using the ```newdev``` branch, that's what worked for my Sabre RGB

**Comment by Ravenslofty** [comment]
Even better, try using [ckb-next](https://github.com/ckb-next/ckb-next), which is actively maintained.

Y'know, like the readme asks you to.

**Comment by alejzeis** [comment]
@ZirconiumX my bad, I did not notice that at all.
