### ISSUE TITLE
Uninstall instructions?

### ISSUE THREAD

**Issue by rayshan** [ccMSC/ckb#61]
Hi, would love to try your firmware and tools. Thanks for spending the time on it. Are there any uninstall instructions? Just in case things don't work. I'm on OS X btw.

**Comment by ccMSC** [comment]
Just drag ckb.app into the trash.

There's also a service file which I *think* will be cleaned up automatically, but if you want to be sure, you can run this in a terminal:
```
sudo rm -f /Library/LaunchDaemons/com.ckb.daemon.plist
```

**Comment by rayshan** [comment]
Thanks!
