### ISSUE TITLE
Volume wheel not working anymore

### ISSUE THREAD

**Issue by Alkeryn** [ccMSC/ckb#618]
Like it isn't even detected in xev anymore though other keyboard works
and the issue isn't with the keyboard since it works on windows ^^

**Comment by ZirconiumX** [comment]
Please try [ckb-next](https://github.com/mattanger/ckb-next/), because ckb itself has not been in development for over a year. The readme says as much.

**Comment by Alkeryn** [comment]
Thanks worked like a charm and it have cool new feature on top :)
