### ISSUE TITLE
Can't Open Color Picker Ubuntu 17.10

### ISSUE THREAD

**Issue by peacockethan** [ccMSC/ckb#620]
Running Pop_OS and stock ubuntu 17.10, ckb freezes when clicking the color option everywhere

**Comment by ZirconiumX** [comment]
1) Please use [ckb-next](https://github.com/mattanger/ckb-next) instead.
2) This is due to a bug in Qt, not due to CKB. There are [workarounds](https://github.com/mattanger/ckb-next#fedora-26-color-changer-freeze-fix) that help.
