### ISSUE TITLE
Doesn't work on CentOS 7

### ISSUE THREAD

**Issue by DarkLogicX** [ccMSC/ckb#625]
I tried this on CentOS 7 and it didn't see my Corsair Scimitar RGB mouse.
I bought the mouse to pair with my Corsair K70 red keyboard but so far I flat out can't use it as when CentOS 7 loads it doesn't even light up the mouse.

I've tested the mouse with windows and it works.

**Comment by Ravenslofty** [comment]
Please use [ckb-next](https://github.com/ckb-next/ckb-next) instead.

**Comment by DarkLogicX** [comment]
Thanks that lead me to
https://copr.fedorainfracloud.org/coprs/johanh/ckb/
And it worked.
