### ISSUE TITLE
K70 RGB not working on Mojave

### ISSUE THREAD

**Issue by niklasbeab** [ccMSC/ckb#631]
Lights are working but my mac doesnt recoignize any key presses from the keyboard

**Comment by jflayhart** [comment]
@niklasbeab same, how'd you fix it?

**Comment by tatokis** [comment]
From the readme:

**This project is no longer maintained.** I simply do not have the time to work on it anymore. Thanks to everyone who helped me to test and develop it.

**An actively-developed version can be found here:** https://github.com/ckb-next/ckb-next

Please check them out instead. Thanks!
