### ISSUE TITLE
Mac OS X modifier keys stop working

### ISSUE THREAD

**Issue by xavierbaez** [ccMSC/ckb#66]
I use Controller Mate to map ALT + HOME to (COMMAND+SHIFT+H)

I also changed the modifier keys on Mac OS X prefernces.

However, when the daemon is running, I can no longer re-map the CONTROL or the COMMAND keys anymore.

**Comment by ccMSC** [comment]
ckb generally conflicts with any other key rebinding software, so you'll need to configure shortcuts in ckb separately. The modifier keys can be remapped from ckb's Settings page (note: you need to have both the daemon and the GUI running for this to work).
