### ISSUE TITLE
General setup isn't working on OSX Yosemite

### ISSUE THREAD

**Issue by BrendanMiller** [ccMSC/ckb#7]
Video of issue: https://www.youtube.com/watch?v=jI2T5Z6UvWY&feature=youtu.be

Hey all!

Really appreciate all the work that's put into this project. I can't figure it out for the life of me, though. I think I'm following all of the instructions for Mac OSX. There's a few hiccups along the way:

1) When configuring the file in QT it's default is set to "iphone", and I have to switch it to Desktop (using iphone didnt work)

2) When building theres 40+ errors (as you can see)

3) Opening the .app file as I normally would open a file brings up the GUI, then an alert pops up and the whole app closes, though "Setting FPS to 30" appears in the terminal window while this happens

What am I doing wrong? :)

Thanks again for any help. Really wish I could use this keyboard!

**Comment by BrendanMiller** [comment]
I should have an update in the next 24 hours, thanks so much for your help so far! So much holiday stuff got in the way of testing :)

**Comment by BrendanMiller** [comment]
Im trying on a different Mac right now (not a macbook) and it's working perfectly! I didn't have to type in any rgb off, manually. The instructions on github worked 100% on this mac. 

Could this be a problem with macbooks? I'll try on a different macbook later today and let you know if I'm encountering the same issue.

**Comment by BrendanMiller** [comment]
You can probably close this "issue" and if I find that it happens on our other couple of macbooks I'll open a new ticket (or you can yourself)

**Comment by ccMSC** [comment]
Ok, fair enough. I can't see why it wouldn't work on a Macbook but let me know what you find. :)
