### ISSUE TITLE
Profiles/modes aren't saving

### ISSUE THREAD

**Issue by juanjalvarez** [ccMSC/ckb#71]
Hi, for some reason whenever I come up with a new mode and restart the computer or quit CKB the mode I had previously made does a rollback of sorts. As far as it has saved is the name of the profile and the name of the mode along with the color of the entire keyboard, but none of the animations.

I'm on Ubuntu 15.04, and I'm using a K70.

**Comment by ccMSC** [comment]
Due to hardware limitations the animations won't work without ckb running. Do they come back when you restart the app?

If they're not being restored, look in `~/.config/ckb` and see if there's a file named `ckb.conf`. The settings should be stored there; if the file is missing or not being updated then that might be the problem.

**Comment by 101Cipher010** [comment]
They do not come back if ckb shuts down. I deleted the conf file and the same thing still happens.

**Comment by ccMSC** [comment]
Does the conf file reappear after being deleted? Can you upload it somewhere (e.g. pastebin) and post it here?

**Comment by 101Cipher010** [comment]
http://pastebin.com/mu3wRhf7

**Comment by ccMSC** [comment]
Well the animations are definitely saved there, so it seems they're not being loaded for some reason. I'll see if I can find out why.

**Comment by 101Cipher010** [comment]
Awesome, thanks

**Comment by ccMSC** [comment]
I think the problem might have been ckb constantly re-loading the hardware profile and getting inconsistent results (it used to do a hardware save every time it exited, but that had its own problems).

There's a fix in [testing](https://github.com/ccMSC/ckb/tree/testing) now, assuming that this is the cause. If it's still not working, I'll put together a debugging build to figure out where the data is being lost.

**Comment by 101Cipher010** [comment]
Still having the same problem

**Comment by ccMSC** [comment]
Hi, sorry it's been such a long time but I assume this was never fixed? I finally got that settings test build I was talking about. You can find it here: https://github.com/ccMSC/ckb/tree/settingtest

After installing, open it in a terminal with `/bin/ckb >~/ckb.log`. This should produce a file called `ckb.log` in your home directory with detailed information about where the settings are and how they're being loaded. Paste the output here and I'll try to figure out what's going on.
