### ISSUE TITLE
No key repeat in virtual terminals

### ISSUE THREAD

**Issue by GigabyteProductions** [ccMSC/ckb#78]
Key repeat works before anything related to ckb is loaded, such as when entering a boot-time encryption pass phrase.

I have not tested on other platforms. I use an Ubuntu 15.04 based distribution. It does not appear to be an Ubuntu or Ubuntu component issue as key repeat works with another ps/2 keyboard.

**Comment by ccMSC** [comment]
Was fixed by 0ce66b3e6d4368a18b7f1a9416e1e510d484dc0e. It's still in the testing repo.
