### ISSUE TITLE
Color scheme based on the currently active window (focus)

### ISSUE THREAD

**Issue by mrueg** [ccMSC/ckb#81]
It would be great to adapt the color scheme, based on the current active application.
 _NET_ACTIVE_WINDOW should be suitable to do that on all common WM. ( _NET_WM_NAME will reveal the name of the active window)
http://standards.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472702304
Using http://tronche.com/gui/x/xlib/events/input-focus/#XFocusChangeEvent one could avoid polling _NET_ACTIVE_WINDOW.

So special color schemes for Gimp, Inkscape etc. could be loaded after the application was started (and drop back to default color scheme if the application looses focus or is terminated).

**Comment by skeate** [comment]
> - **v0.4 release:**
> - Ability to tie profiles to which application has focus
