### ISSUE TITLE
Pinwheel + new animation button - K70 new logo 

### ISSUE THREAD

**Issue by WickedPadfoot** [ccMSC/ckb#83]
Hi, I updated this morning for the 1.5 version and it look like the Pinwheel animation is not working anymore. Also, i can't click on the "new animation" button, it close my GUI but the application is still running. 

Thanks for you great job!
**I tried the windows driver lately and i can't believe how crappy it is compare to your!

**Comment by ccMSC** [comment]
OSX or Linux? Have you tried rebooting and/or reinstalling it?

**Comment by WickedPadfoot** [comment]
I'm on Linux. I have reboot and recompiled it.

**Comment by ccMSC** [comment]
Strange, I'm not able to replicate the problem. You could try compiling [the testing repository](https://github.com/ccMSC/ckb/tree/testing) and see if that helps.

If not, could you send me your `ckb.conf` file? You can find it in `~/.config/ckb/`

**Comment by WickedPadfoot** [comment]
My problem is now solved. I checked out the testing branch but the driver was still the same. I reinstalled it with quickinstall and now it's fine. You did a greath job on that update. Thank you!
