### ISSUE TITLE
Icon is in a wierd location

### ISSUE THREAD

**Issue by timeDev** [ccMSC/ckb#89]
Using Ubuntu 14.04, the ckb icon appears right in the top left corner of the screen, where the x is located, unlike other applications like steam, which are in the top right.

**Comment by ccMSC** [comment]
This is being worked on in the [testing repo](https://github.com/ccMSC/ckb/tree/testing). If you have `libappindicator` installed you can compile that version and it should appear correctly.

**Comment by johnkernke** [comment]
I have a few different versions of `libappindicator` installed:

```
$ dpkg --get-selections | grep libappindicator
libappindicator1				install
libappindicator3-1				install
```

But the way that it checks if it is installed doesn't work.

```
$ pkg-config --exists appindicator-0.1
$ echo $?
1
```

I also tried installing the package `libappindicator0.1-cil-dev` but it also wouldn't get picked up with `pkg-config`.

Any recommendations on how to get it to be picked up, preferably installed through apt.

**Comment by skandalfo** [comment]
libappindicator0.1-cil-dev seems to be the .NET devel package for libappindicator. I think you want just plain libappindicator-dev.

**Comment by johnkernke** [comment]
ah, thanks. that was the package I needed.
