### ISSUE TITLE
K95 RGB won't initialize, then ckb-daemon segfaults

### ISSUE THREAD

**Issue by kamikazejs** [ccMSC/ckb#9]
So I briefly had this working on Christmas on opensuse 13.2 after spending 4 hours fiddling, but now booting into linux again, nothing I do will get the KB working.  I dual boot Win 7, and the KB works there (although it takes about 3 minutes to be properly recognized to where I can type my login information).  Under Windows 7 I have the latest CUE software and it reports the latest firmware on the board.  I've tried 1xUSB3, 2xUSB3, 2xUSB2, etc.  Tried BIOS settings (works in grub menu if done early enough) and at the other polling rates.

I followed the instructions to exclude the device from usbhid btw.

GRUB_CMDLINE_LINUX_DEFAULT=" resume=/dev/disk/by-id/ata-SSD2SC240G5SA754D117-511_PNY24140000527781015-part4 splash=silent quiet showopts usbhid.quirks=0x1B1C:0x1B11:0x20000000"

So now, linux takes >5 minutes (vs 12 seconds with SSD+UEFI) to boot to a login prompt, whereupon the KB doesn't work at all.  I've added a ./ckb-daemon in "/etc/rc.d/after.local" (tried in boot.local but that didn't help either). I'm just getting:

--> Millions of these 

Dec 30 13:15:03 daimyo kernel: usbhid 3-6:1.1: can't add hid device: -110
Dec 30 13:15:03 daimyo kernel: usbhid: probe of 3-6:1.1 failed with error -110
Dec 30 13:15:38 daimyo kernel: usbhid 3-6:1.2: can't add hid device: -110
Dec 30 13:15:38 daimyo kernel: usbhid: probe of 3-6:1.2 failed with error -110
Dec 30 13:16:13 daimyo kernel: usbhid 3-6:1.3: can't add hid device: -110
Dec 30 13:16:13 daimyo kernel: usbhid: probe of 3-6:1.3 failed with error -110
Dec 30 13:16:13 daimyo mtp-probe[10856]: checking bus 3, device 32: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-6"
Dec 30 13:16:13 daimyo mtp-probe[10856]: bus: 3, device: 32 was not an MTP device
Dec 30 13:16:13 daimyo kernel: usb 3-6: Process 10262 (ckb-daemon) called USBDEVFS_CLEAR_HALT for active endpoint 0x81
Dec 30 13:16:28 daimyo kernel: input: ckb1 as /devices/virtual/input/input103
Dec 30 13:16:28 daimyo kernel: usb 3-6: usbfs: USBDEVFS_CONTROL failed cmd ckb-daemon rqt 33 rq 9 len 1 ret -110
Dec 30 13:16:28 daimyo kernel: usb 3-6: usbfs: USBDEVFS_CONTROL failed cmd ckb-daemon rqt 33 rq 9 len 64 ret -110
Dec 30 13:16:28 daimyo kernel: usb 3-6: usbfs: USBDEVFS_CONTROL failed cmd ckb-daemon rqt 33 rq 9 len 64 ret -110
Dec 30 13:16:28 daimyo kernel: usb 3-6: usbfs: USBDEVFS_CONTROL failed cmd ckb-daemon rqt 33 rq 9 len 64 ret -110
Dec 30 13:16:28 daimyo kernel: usb 3-6: usbfs: USBDEVFS_CONTROL failed cmd ckb-daemon rqt 33 rq 9 len 64 ret -110
Dec 30 13:16:29 daimyo kernel: usb 3-6: reset full-speed USB device number 32 using xhci_hcd
Dec 30 13:16:29 daimyo kernel: xhci_hcd 0000:00:14.0: Setup ERROR: setup context command for slot 31.
Dec 30 13:16:29 daimyo kernel: usb 3-6: hub failed to enable device, error -22
Dec 30 13:16:29 daimyo kernel: usb 3-6: reset full-speed USB device number 32 using xhci_hcd
Dec 30 13:16:29 daimyo kernel: xhci_hcd 0000:00:14.0: Setup ERROR: setup context command for slot 31.
Dec 30 13:16:29 daimyo kernel: usb 3-6: hub failed to enable device, error -22
Dec 30 13:16:29 daimyo kernel: usb 3-6: reset full-speed USB device number 32 using xhci_hcd
Dec 30 13:16:29 daimyo kernel: xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff8804066ab2c0
Dec 30 13:16:29 daimyo kernel: xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff8803f709b040
Dec 30 13:16:29 daimyo kernel: xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff8803f709ba40
Dec 30 13:16:29 daimyo kernel: xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff8803d391aa48
Dec 30 13:16:29 daimyo kernel: xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff8803d391aa00
Dec 30 13:16:30 daimyo kernel: usb 3-6: usbfs: process 10904 (ckb-daemon) did not claim interface 0 before use
Dec 30 13:16:30 daimyo kernel: usb 3-6: usbfs: process 10904 (ckb-daemon) did not claim interface 1 before use
Dec 30 13:16:30 daimyo kernel: usb 3-6: usbfs: process 10904 (ckb-daemon) did not claim interface 2 before use
Dec 30 13:18:36 daimyo kernel: usb 3-6: USB disconnect, device number 32
Dec 30 13:18:37 daimyo kernel: usb 3-6: new full-speed USB device number 33 using xhci_hcd
Dec 30 13:18:47 daimyo kernel: usb 3-6: New USB device found, idVendor=1b1c, idProduct=1b11
Dec 30 13:18:47 daimyo kernel: usb 3-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec 30 13:18:47 daimyo kernel: usb 3-6: Product: Corsair K95 RGB Gaming Keyboard
Dec 30 13:18:47 daimyo kernel: usb 3-6: Manufacturer: Corsair
Dec 30 13:18:52 daimyo kernel: usb 3-6: can't set config #1, error -110
Dec 30 13:18:52 daimyo mtp-probe[11349]: checking bus 3, device 33: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-6"
Dec 30 13:18:52 daimyo mtp-probe[11349]: bus: 3, device: 33 was not an MTP device

And after 10 minutes, it just segfaults.

Dec 30 13:18:52 daimyo kernel: ckb-daemon[10262]: segfault at 0 ip 00007f0b35f92b2f sp 00007f0b3347edb8 error 4 in libc-2.19.so[7f0b35efd000+19e000]

daimyo:~ # ckb-daemon 
ckb Corsair Keyboard RGB driver v0.0.18
Setting FPS to 30
Setting default layout: us
Root controller ready at /dev/input/ckb0
Segmentation fault

Dec 30 13:26:53 daimyo kernel: ckb-daemon[12938]: segfault at 0 ip 00007f8792032b2f sp 00007f878f51ed78 error 4 in libc-2.19.so[7f8791f9d000+19e000]

If I unplug the KB and plug it back in, then restart ckb-daemon, I'll get the hid device: -110 errors, systemd-udevd error, and it still eventually segfaults (sometimes immediately, sometimes after the 25 loops of resets).

Any advice or things to try?  Should I yell at Corsair or just return it?  If I could get this working under Linux then I might keep it.  It's such a beautiful piece of work, mechanically and electronically, to be hobbled by such flakiness.

**Comment by lathiat** [comment]
Not sure if the same crash but I get the same output.

ckb was working fine until I rebooted just now and the keyboard doesn't appear re-initialised (still has some RGB stuff on it).  I currently have quirks set on the kernel cmdline

(gdb) run
Starting program: /home/lathiat/src/ckb/bin/ckb-daemon 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
ckb Corsair Keyboard RGB driver alpha-v0.0.35
Setting FPS to 30
Setting default layout: us
Root controller ready at /dev/input/ckb0
[New Thread 0x7ffff731c700 (LWP 4965)]
[New Thread 0x7ffff6b1b700 (LWP 4966)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff731c700 (LWP 4965)]
__strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:296
296	../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:296
#1  0x000000000040c269 in openusb (dev=0x7ffff0000e70, vendor=6940, product=6929) at usb_linux.c:235
#2  0x000000000040c753 in udevenum () at usb_linux.c:357
#3  0x000000000040c7dc in udevmain (context=0x0) at usb_linux.c:371
#4  0x00007ffff79b30a5 in start_thread (arg=0x7ffff731c700) at pthread_create.c:309
#5  0x00007ffff76e090d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) up
#1  0x000000000040c269 in openusb (dev=0x7ffff0000e70, vendor=6940, product=6929) at usb_linux.c:235
235	            strncpy(kb->name, udev_device_get_sysattr_value(dev, "product"), NAME_LEN);
(gdb) l
230	                kb->udev = 0;
231	                return -1;
232	            }
233	
234	            // Copy device description and serial
235	            strncpy(kb->name, udev_device_get_sysattr_value(dev, "product"), NAME_LEN);
236	            const char* serial = udev_device_get_sysattr_value(dev, "serial");
237	            if(serial)
238	                strncpy(kb->profile.serial, serial, SERIAL_LEN);
239	            else

**Comment by lathiat** [comment]
Corefile: http://lathi.at/files/ckb.core

(gdb) backtrace full
#0  __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:296
No locals.
#1  0x000000000040c269 in openusb (dev=0x7ffff0000e70, vendor=6940, product=6929) at usb_linux.c:235
        serial = 0x1 <error: Cannot access memory at address 0x1>
        setup = 4263248
        index = 0
        kb = 0x616950 <keyboard+1168>
        index = 1
        path = 0x7ffff0001990 "/dev/bus/usb/001/002"
#2  0x000000000040c753 in udevenum () at usb_linux.c:357
        model = 0x6163b0 <models+48>
        path = 0x7ffff0000db0 "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
        dev = 0x7ffff0000e70
        product = 0x7ffff00013b0 "1b11"
        found = 1
        enumerator = 0x7ffff00008c0
        devices = 0x7ffff0000d70
        dev_list_entry = 0x7ffff0000d70
#3  0x000000000040c7dc in udevmain (context=0x0) at usb_linux.c:371
        tries = 0
        monitor = 0x0
        fd = 0
        fds = {fds_bits = {0, 0, 128, 140737347535409, 0, 140737343584544, 140737340622592, 0, 1, 140737351976245, 0, 
            140737347530820, 140737340622592, 24, 140737340620592, 140737340622592}}
#4  0x00007ffff79b30a5 in start_thread (arg=0x7ffff731c700) at pthread_create.c:309
        __res = <optimised out>
        pd = 0x7ffff731c700
        now = <optimised out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737340622592, -2586622876933452336, 1, 0, 140737340623296, 
                140737340622592, 2586638839157853648, 2586639607863021008}, mask_was_saved = 0}}, priv = {pad = {0x0, 
              0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimised out>
        pagesize_m1 = <optimised out>
        sp = <optimised out>
---Type <return> to continue, or q <return> to quit---
        freesize = <optimised out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff76e090d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
(gdb)

**Comment by lathiat** [comment]
Unplugged/re-plugged the keyboard and it works OK

**Comment by ccMSC** [comment]
Based on that trace it looks like it died after getting a null string from udev. As of commit 20cadbec9acfd3902e700940253ef04668126195 it should be fixed, along with all of the other udev values that I could find. This is a pretty old issue, so I'm going to close it for now - feel free to open a new one if it crashes anywhere else.
