### ISSUE TITLE
ckb background process takes too much cpu?

### ISSUE THREAD

**Issue by SethDusek** [ccMSC/ckb#91]
So, i installed ckb, and while htop was open I've noticed it takes a lot of CPU, usually being at the top of the list. https://i.imgur.com/Izm6mIN.png

Is there any fix to this?

**Comment by ccMSC** [comment]
No, that's normal. It might be improved in the future but I can't make any guarantees.

**Comment by ccMSC** [comment]
Closing this issue as the discussion has moved to #67. The problem will be worked on in a future version.
