### ISSUE TITLE
Ok I just found this Amazing project

### ISSUE THREAD

**Issue by badgero1234** [ccMSC/ckb#97]
What Can I do for you regarding testing. Also on another related note; How difficult will it be to include the RGB Stafe model just announced a few hours ago, same keyboard Idea. What would need to change in the code? I am learning c and I figure if I have a project this will help me learn quicker. Thanks for your amazing work.

**Comment by badgero1234** [comment]
also I am coding on a mac

**Comment by mrueg** [comment]
See https://github.com/ccMSC/ckb/issues/94

**Comment by badgero1234** [comment]
so how difficult will it be to add a new keyboard? like the strafe RGB?

**Comment by ccMSC** [comment]
Depends entirely on how different the USB protocol is. It could be a simple matter of adding it to the supported devices, or it could require a complete rewrite. We won't know until it's released and someone gets the USB captures from the Windows driver.

(Closing this issue as a duplicate of #94 - feel free to continue the discussion there)
